swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Asset And Liability Management'
 description: >

    ## Executive Summary:

    The unit overseeing the banks asset And liability policies and position

    ## Example of Use:

    The bank's senior policy makers review that bank's book performance and amend guidelines to remain within policy directives

    ## Description:

    A central policy and direction capability that reviews consolidated bank PAndL profile and performance and defines and directs asset and liability policies. Also sanctions and/or influences large transactions

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-asset-and-liability-management/1.0.0
schemes:
 - https
paths:
  /asset-and-liability-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDAssetAndLiabilityManagement
      summary: Activate  a SDAssetAndLiabilityManagement servicing session
      description: Activate  a  SDAssetAndLiabilityManagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityManagement Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityManagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityManagementActivateOutputModel'
  /asset-and-liability-management/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDAssetAndLiabilityManagement
      summary: Update an active SDAssetAndLiabilityManagement session configuration
      description: Update an active SDAssetAndLiabilityManagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityManagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityManagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityManagementConfigureOutputModel'
  /asset-and-liability-management/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDAssetAndLiabilityManagement
      summary: "Capturing feedback against the SDAssetAndLiabilityManagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDAssetAndLiabilityManagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityManagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityManagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityManagementFeedbackOutputModel'
  /asset-and-liability-management/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDAssetAndLiabilityManagement
      summary: Analytical views maintained by the SDAssetAndLiabilityManagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDAssetAndLiabilityManagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityManagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDAssetAndLiabilityManagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityManagementRetrieveOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateAssetAndLiabilityPortfolioStrategy
      summary: Update to any amendable fields of the AssetAndLiabilityPortfolioStrategy instance
      description: Update aspects of the bank's asset and liability policies
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyUpdateOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestAssetAndLiabilityPortfolioStrategyUpdate
      summary: Invoke a service request action against the AssetAndLiabilityPortfolioStrategy instance
      description: Request manual intervention in the policies (e.g. request revision based on regulatory changes)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRequestInputModel'
      responses:
        200:
          description: Successful requisition of Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRequestOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantAssetAndLiabilityPortfolioStrategyUpdate
      summary: Invoke a grant request action from the AssetAndLiabilityPortfolioStrategy instance to obtain access permission
      description: Obtain a permission grant in line with asset and liability policy (e.g. clearance for some related financial action)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyGrantInputModel'
      responses:
        200:
          description: Successful grant of Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyGrantOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveAssetAndLiabilityManagement
      summary: Invoke a reporting action to obtain a Asset And Liability Portfolio Strategy instance related report
      description: Retrieve details about the bank's asset and liability policies
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRAssetAndLiabilityPortfolioStrategyRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRetrieveOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/transactionalignment/creation:
    post:
      tags:
      - create
      operationId: createAssetAndLiabilityPortfolioStrategyTransactionAlignment
      summary: Details of a new TransactionAlignment instance
      description: Create a proposed transaction submission under the policy
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/BQTransactionAlignmentCreateInputModel'
      responses:
        201:
          description: Successful creation of Asset And Liability Portfolio Strategy instance
          schema:
            $ref: '#/definitions/BQTransactionAlignmentCreateOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/transactionalignment/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeAssetAndLiabilityPortfolioStrategyTransactionAlignmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Verify, accept, etc. aspects of a transaction alignment assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionAlignment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionAlignment request payload
        schema:
          $ref: '#/definitions/BQTransactionAlignmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of TransactionAlignment Instance Record
          schema:
            $ref: '#/definitions/BQTransactionAlignmentExchangeOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/transactionalignment/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestAssetAndLiabilityPortfolioStrategyTransactionAlignmentUpdate
      summary: Invoke a service request action against the TransactionAlignment instance
      description: Request manual intervention during an assessment (e.g. negotiate terms)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionAlignment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionAlignment request payload
        schema:
          $ref: '#/definitions/BQTransactionAlignmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of TransactionAlignment Instance Record
          schema:
            $ref: '#/definitions/BQTransactionAlignmentRequestOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/transactionalignment/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveAssetAndLiabilityPortfolioStrategyTransactionAlignment
      summary: Invoke a reporting action to obtain a TransactionAlignment instance related report.
      description: Retrieve details about a transaction alignment assessment .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionAlignment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTransactionAlignmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved TransactionAlignment Instance Record
          schema:
            $ref: '#/definitions/BQTransactionAlignmentRetrieveOutputModel'
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- AssetAndLiabilityManagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /asset-and-liability-management/asset-and-liability-portfolio-strategy/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'TransactionAlignment', ]
  /asset-and-liability-management/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- TransactionAlignment
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionAlignment Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [TransactionAlignmentID1, TransactionAlignmentID2]
