swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Asset And Liability Mnagement'
 description: >

    ## Executive Summary:

    The unit overseeing the banks asset And liability policies and position

    ## Example of Use:

    The bank's senior policy makers review that bank's book performance and amend guidelines to remain within policy directives

    ## Description:

    A central policy and direction capability that reviews consolidated bank PAndL profile and performance and defines and directs asset and liability policies. Also sanctions and/or influences large transactions

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-asset-and-liability-mnagement/1.0.0
schemes:
 - https
paths:
  /asset-and-liability-mnagement/activation:
    post:
      tags:
      - activate
      operationId: activateSDAssetAndLiabilityMnagement
      summary: Activate  a SDAssetAndLiabilityMnagement servicing session
      description: Activate  a  SDAssetAndLiabilityMnagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityMnagement Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityMnagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityMnagementActivateOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDAssetAndLiabilityMnagement
      summary: Update an active SDAssetAndLiabilityMnagement session configuration
      description: Update an active SDAssetAndLiabilityMnagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityMnagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityMnagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityMnagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityMnagementConfigureOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDAssetAndLiabilityMnagement
      summary: "Capturing feedback against the SDAssetAndLiabilityMnagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDAssetAndLiabilityMnagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityMnagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDAssetAndLiabilityMnagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDAssetAndLiabilityMnagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityMnagementFeedbackOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDAssetAndLiabilityMnagement
      summary: Analytical views maintained by the SDAssetAndLiabilityMnagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDAssetAndLiabilityMnagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDAssetAndLiabilityMnagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDAssetAndLiabilityMnagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDAssetAndLiabilityMnagementRetrieveOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateAssetAndLiabilityPortfolioStrategy
      summary: Details of a new AssetAndLiabilityPortfolioStrategy instance
      description: Evaluate the suitability of a proposed transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: AssetAndLiabilityPortfolioStrategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new AssetAndLiabilityPortfolioStrategy instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyEvaluateOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateAssetAndLiabilityPortfolioStrategy
      summary: Update to any amendable fields of the AssetAndLiabilityPortfolioStrategy instance
      description: Update details of a suitability evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyUpdateOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeAssetAndLiabilityPortfolioStrategyUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject, etc. aspects of a suitability evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyExchangeOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestAssetAndLiabilityPortfolioStrategyUpdate
      summary: Invoke a service request action against the AssetAndLiabilityPortfolioStrategy instance
      description: Request manual intervention into an active evaluation (e.g. consider additional input)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRequestInputModel'
      responses:
        200:
          description: Successful requisition of Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRequestOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantAssetAndLiabilityPortfolioStrategyUpdate
      summary: Invoke a grant request action from the AssetAndLiabilityPortfolioStrategy instance to obtain access permission
      description: Obtain a permission grant associated with the evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Asset And Liability Portfolio Strategy Request Payload
        schema:
          $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyGrantInputModel'
      responses:
        200:
          description: Successful grant of Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyGrantOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveAssetAndLiabilityMnagement
      summary: Invoke a reporting action to obtain a Asset And Liability Portfolio Strategy instance related report
      description: Retrieve details about a suitability evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRAssetAndLiabilityPortfolioStrategyRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Asset And Liability Portfolio Strategy Instance
          schema:
            $ref: '#/definitions/CRAssetAndLiabilityPortfolioStrategyRetrieveOutputModel'
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityMnagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- AssetAndLiabilityMnagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /asset-and-liability-mnagement/asset-and-liability-portfolio-strategy/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityMnagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'TransactionAlignment', ]
  /asset-and-liability-mnagement/{sd-reference-id}/asset-and-liability-portfolio-strategy/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveAssetAndLiabilityMnagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Asset And Liability Mnagement Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Asset And Liability Portfolio Strategy Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- TransactionAlignment
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionAlignment Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [TransactionAlignmentID1, TransactionAlignmentID2]
