swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Competitor Analysis'
 description: >

    ## Executive Summary:

    Solicit, consolidate and analyze competitor specific public domain data to develop competitor insights and comparisons

    ## Example of Use:

    Example of use: A product design unit obtains competitor analysis in order to refine product requirements

    ## Description:

    This service domain provides the range of competitor analysis that inform and support product and service design and business development activities and decisions. It draws on external market research and internal business intelligence gathering as necessary. A standard set of analytical views can be defined and maintained as well as targeted ad-hoc analysis as necessary

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-competitor-analysis/1.0.0
schemes:
 - https
paths:
  /competitor-analysis/activation:
    post:
      tags:
      - activate
      operationId: activateSDCompetitorAnalysis
      summary: Activate  a SDCompetitorAnalysis servicing session
      description: Activate  a  SDCompetitorAnalysis servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCompetitorAnalysis Request Payload
        schema:
          $ref: '#/definitions/SDCompetitorAnalysisActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDCompetitorAnalysisActivateOutputModel'
  /competitor-analysis/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDCompetitorAnalysis
      summary: Update an active SDCompetitorAnalysis session configuration
      description: Update an active SDCompetitorAnalysis session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCompetitorAnalysis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCompetitorAnalysis Configure Request Payload
        schema:
          $ref: '#/definitions/SDCompetitorAnalysisConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDCompetitorAnalysisConfigureOutputModel'
  /competitor-analysis/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDCompetitorAnalysis
      summary: "Capturing feedback against the SDCompetitorAnalysis service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDCompetitorAnalysis service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCompetitorAnalysis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCompetitorAnalysis Feedback Request Payload
        schema:
          $ref: '#/definitions/SDCompetitorAnalysisFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDCompetitorAnalysisFeedbackOutputModel'
  /competitor-analysis/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDCompetitorAnalysis
      summary: Analytical views maintained by the SDCompetitorAnalysis service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDCompetitorAnalysis service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCompetitorAnalysis Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDCompetitorAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDCompetitorAnalysisRetrieveOutputModel'
  /competitor-analysis/{sd-reference-id}/compeitor-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateCompeitorAnalysis
      summary: Details of a new CompeitorAnalysis instance
      description: Initialize competitor analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CompeitorAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRCompeitorAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new CompeitorAnalysis instance
          schema:
            $ref: '#/definitions/CRCompeitorAnalysisEvaluateOutputModel'
  /competitor-analysis/{sd-reference-id}/compeitor-analysis/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCompeitorAnalysisUpdate
      summary: Invoke an automated execute action against the CompeitorAnalysis instance
      description: Obtain an automated refresh of maintained competitor analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Compeitor Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Compeitor Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCompeitorAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of Compeitor Analysis Instance
          schema:
            $ref: '#/definitions/CRCompeitorAnalysisExecuteOutputModel'
  /competitor-analysis/{sd-reference-id}/compeitor-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCompeitorAnalysisUpdate
      summary: Invoke a service request action against the CompeitorAnalysis instance
      description: Request a manual intervention in the development of competitor analysis (in particular for an ad-hoc analysis)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Compeitor Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Compeitor Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCompeitorAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Compeitor Analysis Instance
          schema:
            $ref: '#/definitions/CRCompeitorAnalysisRequestOutputModel'
  /competitor-analysis/{sd-reference-id}/compeitor-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCompetitorAnalysis
      summary: Invoke a reporting action to obtain a Compeitor Analysis instance related report
      description: Retrieve details about competitor analysis activity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Compeitor Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRCompeitorAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Compeitor Analysis Instance
          schema:
            $ref: '#/definitions/CRCompeitorAnalysisRetrieveOutputModel'
  /competitor-analysis/{sd-reference-id}/compeitor-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveCompetitorAnalysisReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- CompetitorAnalysis Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /competitor-analysis/compeitor-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCompetitorAnalysisBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'AnalysisAlgorithm', ]
  /competitor-analysis/{sd-reference-id}/compeitor-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCompetitorAnalysisBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Competitor Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Compeitor Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- AnalysisAlgorithm
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- AnalysisAlgorithm Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [AnalysisAlgorithmID1, AnalysisAlgorithmID2]
