cp AssetAndLiabilityManagement.yaml ../scripts/FinalSwaggers/
cp CashManagmentAndAccountServices.yaml ../scripts/FinalSwaggers/
cp ChannelActivityAnalysis.yaml ../scripts/FinalSwaggers/
cp ChannelActivityHistory.yaml ../scripts/FinalSwaggers/
cp ConsumerLoan.yaml ../scripts/FinalSwaggers/
cp ContactHandler.yaml ../scripts/FinalSwaggers/
cp CorporateCurrentAccount.yaml ../scripts/FinalSwaggers/
cp CorporateDeposits.yaml ../scripts/FinalSwaggers/
cp CurrentAccount.yaml ../scripts/FinalSwaggers/
cp CustomerBehaviorModels.yaml ../scripts/FinalSwaggers/
cp CustomerCreditRating.yaml ../scripts/FinalSwaggers/
cp CustomerEventHistory.yaml ../scripts/FinalSwaggers/
cp CustomerOffer.yaml ../scripts/FinalSwaggers/
cp CustomerRelationshipManagement.yaml ../scripts/FinalSwaggers/
cp CustomerTaxHandling.yaml ../scripts/FinalSwaggers/
cp CustomerWorkbench.yaml ../scripts/FinalSwaggers/
cp DelinquentAccountHandling.yaml ../scripts/FinalSwaggers/
cp DepositAccount.yaml ../scripts/FinalSwaggers/
cp DirectDebitMandate.yaml ../scripts/FinalSwaggers/
cp Disbursement.yaml ../scripts/FinalSwaggers/
cp DocumentServices.yaml ../scripts/FinalSwaggers/
cp EBranchOperations.yaml ../scripts/FinalSwaggers/
cp FinancialAccounting.yaml ../scripts/FinalSwaggers/
cp FinancialGateway.yaml ../scripts/FinalSwaggers/
cp FraudDiagnosis.yaml ../scripts/FinalSwaggers/
cp FraudEvaluation.yaml ../scripts/FinalSwaggers/
cp FraudModels.yaml ../scripts/FinalSwaggers/
cp FraudResolution.yaml ../scripts/FinalSwaggers/
cp GuidelineCompliance.yaml ../scripts/FinalSwaggers/
cp InformationProviderOperation.yaml ../scripts/FinalSwaggers/
cp IssuedDeviceAdministration.yaml ../scripts/FinalSwaggers/
cp IssuedDeviceTracking.yaml ../scripts/FinalSwaggers/
cp LeadOpportunityManagement.yaml ../scripts/FinalSwaggers/
cp LocationDataManagement.yaml ../scripts/FinalSwaggers/
cp MarketAnalysis.yaml ../scripts/FinalSwaggers/
cp MarketDataSwitchOperation.yaml ../scripts/FinalSwaggers/
cp MarketResearch.yaml ../scripts/FinalSwaggers/
cp MerchantAcquiringFacility.yaml ../scripts/FinalSwaggers/
cp OpenItemManagement.yaml ../scripts/FinalSwaggers/
cp PartyAuthentication.yaml ../scripts/FinalSwaggers/
cp PartyDataManagement.yaml ../scripts/FinalSwaggers/
cp PartyLifeCycleManagement.yaml ../scripts/FinalSwaggers/
cp PaymentExecution.yaml ../scripts/FinalSwaggers/
cp PaymentInitiation.yaml ../scripts/FinalSwaggers/
cp PaymentOrder.yaml ../scripts/FinalSwaggers/
cp PointOfService.yaml ../scripts/FinalSwaggers/
cp PositionKeeping.yaml ../scripts/FinalSwaggers/
cp PositionManagement.yaml ../scripts/FinalSwaggers/
cp ProductBrokerAgreement.yaml ../scripts/FinalSwaggers/
cp ProductDirectory.yaml ../scripts/FinalSwaggers/
cp ProductMatching.yaml ../scripts/FinalSwaggers/
cp RegulatoryCompliance.yaml ../scripts/FinalSwaggers/
cp RegulatoryReporting.yaml ../scripts/FinalSwaggers/
cp SalesProductAgreement.yaml ../scripts/FinalSwaggers/
cp SavingsAccount.yaml ../scripts/FinalSwaggers/
cp ServicingEventHistory.yaml ../scripts/FinalSwaggers/
cp ServicingMandate.yaml ../scripts/FinalSwaggers/
cp ServicingOrder.yaml ../scripts/FinalSwaggers/
cp Underwriting.yaml ../scripts/FinalSwaggers/
