swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - CorrespondentBankDataManagement'
 description: >
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-correspondentbankdatamanagement/1.0.0
schemes:
 - https
paths:
  /correspondent-bank-data-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDCorrespondentBank
      summary: Reference to a service activation service call
      description: Reference to a service activation service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCorrespondentBank Request Payload
        schema:
          $ref: '#/definitions/SDCorrespondentBankActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDCorrespondentBankActivateOutputModel'
  /correspondent-bank-data-management/configure:
    put:
      tags:
      - configure
      operationId: configureSDCorrespondentBank
      summary: Reference to a service configuration service call
      description: Reference to a service configuration service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCorrespondentBank Configure Request Payload
        schema:
          $ref: '#/definitions/SDCorrespondentBankConfigureInputModel'
      responses:
        201:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDCorrespondentBankConfigureOutputModel'
  /correspondent-bank-data-management/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDCorrespondentBank
      summary: Reference to a feedback service call
      description: Reference to a feedback service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCorrespondentBank Feedback Request Payload
        schema:
          $ref: '#/definitions/SDCorrespondentBankFeedbackInputModel'
      responses:
        201:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDCorrespondentBankFeedbackOutputModel'
  /correspondent-bank-data-management/retrieve:
    get:
      tags:
      - retrieve
      operationId: retrieveSDCorrespondentBank
      summary: Reference to a retrieve service call
      description: Reference to a retrieve service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCorrespondentBank Retrieve Request Payload
        schema:
          $ref: '#/definitions/SDCorrespondentBankRetrieveInputModel'
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDCorrespondentBankRetrieveOutputModel'
  /correspondent-bank-data-management/correspondent-bank-directory-entry/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorrespondentBankDirectoryEntry
      summary: Details of a new Correspondent Bank Directory Entry instance
      description: Register a new correspondent bank in the catalog
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: CorrespondentBankDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRCorrespondentBankDirectoryEntryInitiateInputModel'
      responses:
        201:
          description: Successful Details of a new Correspondent Bank Directory Entry instance
          schema:
            $ref: '#/definitions/CRCorrespondentBankDirectoryEntryInitiateOutputModel'
  /correspondent-bank-data-management/correspondent-bank-directory-entry/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateCorrespondentBankDirectoryEntry
      summary: Update to any amendable fields of the Correspondent Bank Directory Entry instance
      description: Update details of a correspondent bank in the catalog
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: CR Correspondent Bank Directory Entry Instance Record
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CorrespondentBankDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRCorrespondentBankDirectoryEntryUpdateInputModel'
      responses:
        200:
          description: Successful Update to any amendable fields of the Correspondent Bank Directory Entry instance
          schema:
            $ref: '#/definitions/CRCorrespondentBankDirectoryEntryUpdateOutputModel'
  /correspondent-bank-data-management/correspondent-bank-directory-entry/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCorrespondentBankDirectoryEntryUpdate
      summary: Invoke a service request action against the Correspondent Bank Directory Entry instance
      description: Request that an existing entry is updated or revised
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: CR Correspondent Bank Directory Entry Instance Record
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CorrespondentBankDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRCorrespondentBankDirectoryEntryRequestInputModel'
      responses:
        200:
          description: Successful Invoke a service request action against the Correspondent Bank Directory Entry instance
          schema:
            $ref: '#/definitions/CRCorrespondentBankDirectoryEntryRequestOutputModel'
  /correspondent-bank-data-management/correspondent-bank-directory-entry:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorrespondentBankDataManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- CorrespondentBank Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /correspondent-bank-data-management/correspondent-bank-directory-entry/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorrespondentBankDataManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /correspondent-bank-data-management/correspondent-bank-directory-entry/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorrespondentBankDataManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: CR Correspondent Bank Directory Entry Instance Record
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
  /correspondent-bank-data-management/correspondent-bank-directory-entry/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorrespondentBankDataManagement
      summary: Retrieve a CorrespondentBankDataManagement Record
      description: Retrieve a CorrespondentBankDataManagement Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: CR Correspondent Bank Directory Entry Instance Record
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CorrespondentBankDataManagement Request Payload
        schema:
          $ref: '#/definitions/CRCorrespondentBankDataManagementRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved CorrespondentBankDataManagement Report
          schema:
            $ref: '#/definitions/CRCorrespondentBankDataManagementRetrieveOutputModel'
