swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Customer Behavioral Insights'
 description: >

    ## Executive Summary:

    This service domain applies behavioral analysis to customer event history to maintain a range of customer ratings/scores (such as 'propensity to buy') and to detect life events or trends

    ## Example of Use:

    A regular analysis of customer event histories is used to update the maintained range of customer behavioral insights. The updated results are notified to the Customer Relationship Management and Party Profile Service Domains as appropriate

    ## Description:

    This service domain references the range of customer historical data maintained by the Customer Event History service domain to develop behavioral insights into customers. This analysis can support sales and marketing activity (e.g. by determining the likely response to sales efforts based on passed performance) as well as identifying changes in status and behavior that might influence the desired product mix for a customer. The actual analysis routines are developed/maintained by the Customer Behavior Models service domain

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-customer-behavioral-insights/1.0.0
schemes:
 - https
paths:
  /customer-behavioral-insights/activation:
    post:
      tags:
      - activate
      operationId: activateSDCustomerBehavioralInsights
      summary: Activate  a SDCustomerBehavioralInsights servicing session
      description: Activate  a  SDCustomerBehavioralInsights servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCustomerBehavioralInsights Request Payload
        schema:
          $ref: '#/definitions/SDCustomerBehavioralInsightsActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDCustomerBehavioralInsightsActivateOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDCustomerBehavioralInsights
      summary: Update an active SDCustomerBehavioralInsights session configuration
      description: Update an active SDCustomerBehavioralInsights session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerBehavioralInsights Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCustomerBehavioralInsights Configure Request Payload
        schema:
          $ref: '#/definitions/SDCustomerBehavioralInsightsConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDCustomerBehavioralInsightsConfigureOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDCustomerBehavioralInsights
      summary: "Capturing feedback against the SDCustomerBehavioralInsights service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDCustomerBehavioralInsights service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerBehavioralInsights Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCustomerBehavioralInsights Feedback Request Payload
        schema:
          $ref: '#/definitions/SDCustomerBehavioralInsightsFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDCustomerBehavioralInsightsFeedbackOutputModel'
  /customer-behavioral-insights/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDCustomerBehavioralInsights
      summary: Analytical views maintained by the SDCustomerBehavioralInsights service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDCustomerBehavioralInsights service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerBehavioralInsights Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDCustomerBehavioralInsightsRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDCustomerBehavioralInsightsRetrieveOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateCustomerBehaviorAnalysis
      summary: Details of a new CustomerBehaviorAnalysis instance
      description: Set-up evaluation of customer behavior insights for a customer
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CustomerBehaviorAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerBehaviorAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new CustomerBehaviorAnalysis instance
          schema:
            $ref: '#/definitions/CRCustomerBehaviorAnalysisEvaluateOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeCustomerBehaviorAnalysisUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify, etc. customer behavior insights
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Behavior Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerBehaviorAnalysisExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Customer Behavior Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerBehaviorAnalysisExchangeOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCustomerBehaviorAnalysisUpdate
      summary: Invoke an automated execute action against the CustomerBehaviorAnalysis instance
      description: Execute an automated task for customer insights (e.g. automated refresh
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Behavior Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerBehaviorAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of Customer Behavior Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerBehaviorAnalysisExecuteOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCustomerBehaviorAnalysisUpdate
      summary: Invoke a service request action against the CustomerBehaviorAnalysis instance
      description: Request manual intervention for customer insights (e.g. unscheduled revision)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Behavior Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerBehaviorAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Customer Behavior Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerBehaviorAnalysisRequestOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCustomerBehavioralInsights
      summary: Invoke a reporting action to obtain a Customer Behavior Analysis instance related report
      description: Retrieve details about customer behavior insights
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRCustomerBehaviorAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Customer Behavior Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerBehaviorAnalysisRetrieveOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/insight/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeCustomerBehaviorAnalysisInsightUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify etc. a selected type of customer behavior insight
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Insight Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Insight request payload
        schema:
          $ref: '#/definitions/BQInsightExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Insight Instance Record
          schema:
            $ref: '#/definitions/BQInsightExchangeOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/insight/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCustomerBehaviorAnalysisInsightUpdate
      summary: Invoke an automated execute action against the Insight instance
      description: Execute an automated task for a specific customer behavior insight (e.g. refresh)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Insight Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Insight request payload
        schema:
          $ref: '#/definitions/BQInsightExecuteInputModel'
      responses:
        200:
          description: Successful execution of Insight Instance Record
          schema:
            $ref: '#/definitions/BQInsightExecuteOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/insight/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCustomerBehaviorAnalysisInsightUpdate
      summary: Invoke a service request action against the Insight instance
      description: Request manual intervention for a specific customer behavior insight (e.g. re-calculate)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Insight Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Insight request payload
        schema:
          $ref: '#/definitions/BQInsightRequestInputModel'
      responses:
        200:
          description: Successful requisition of Insight Instance Record
          schema:
            $ref: '#/definitions/BQInsightRequestOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/insight/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveCustomerBehaviorAnalysisInsight
      summary: Invoke a reporting action to obtain a Insight instance related report.
      description: Retrieve details about a specific customer behavior insight .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Insight Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQInsightRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Insight Instance Record
          schema:
            $ref: '#/definitions/BQInsightRetrieveOutputModel'
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerBehavioralInsightsReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- CustomerBehavioralInsights Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /customer-behavioral-insights/customer-behavior-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerBehavioralInsightsBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Insight', ]
  /customer-behavioral-insights/{sd-reference-id}/customer-behavior-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerBehavioralInsightsBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Behavioral Insights Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Behavior Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Insight
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Insight Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [InsightID1, InsightID2]
