swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Customer Portfolio'
 description: >

    ## Executive Summary:

    Maintain a portfolio of analytical views of the customer base to support customer segment profitability and performance analysis

    ## Example of Use:

    Business development review customer segment performance in order to target customer relationship management priorities

    ## Description:

    Maintain a portfolio of view of the customer base with key customer data and consolidated activity details to support profitability and performance analysis across many possible customer segment dimensions

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-customer-portfolio/1.0.0
schemes:
 - https
paths:
  /customer-portfolio/activation:
    post:
      tags:
      - activate
      operationId: activateSDCustomerPortfolio
      summary: Activate  a SDCustomerPortfolio servicing session
      description: Activate  a  SDCustomerPortfolio servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDCustomerPortfolio Request Payload
        schema:
          $ref: '#/definitions/SDCustomerPortfolioActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDCustomerPortfolioActivateOutputModel'
  /customer-portfolio/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDCustomerPortfolio
      summary: Update an active SDCustomerPortfolio session configuration
      description: Update an active SDCustomerPortfolio session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerPortfolio Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCustomerPortfolio Configure Request Payload
        schema:
          $ref: '#/definitions/SDCustomerPortfolioConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDCustomerPortfolioConfigureOutputModel'
  /customer-portfolio/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDCustomerPortfolio
      summary: "Capturing feedback against the SDCustomerPortfolio service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDCustomerPortfolio service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerPortfolio Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDCustomerPortfolio Feedback Request Payload
        schema:
          $ref: '#/definitions/SDCustomerPortfolioFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDCustomerPortfolioFeedbackOutputModel'
  /customer-portfolio/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDCustomerPortfolio
      summary: Analytical views maintained by the SDCustomerPortfolio service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDCustomerPortfolio service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDCustomerPortfolio Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDCustomerPortfolioRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDCustomerPortfolioRetrieveOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateCustomerSegmentAnalysis
      summary: Details of a new CustomerSegmentAnalysis instance
      description: Evaluate customer segment performance (trigger the analysis)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CustomerSegmentAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerSegmentAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new CustomerSegmentAnalysis instance
          schema:
            $ref: '#/definitions/CRCustomerSegmentAnalysisEvaluateOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateCustomerSegmentAnalysis
      summary: Update to any amendable fields of the CustomerSegmentAnalysis instance
      description: Update settings or content for customer segment analysis activity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Segment Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerSegmentAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Customer Segment Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerSegmentAnalysisUpdateOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCustomerSegmentAnalysisUpdate
      summary: Invoke a service request action against the CustomerSegmentAnalysis instance
      description: Request manual intervention in the customer segment analysis activity (e.g. ad-hoc request)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Segment Analysis Request Payload
        schema:
          $ref: '#/definitions/CRCustomerSegmentAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Customer Segment Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerSegmentAnalysisRequestOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCustomerPortfolio
      summary: Invoke a reporting action to obtain a Customer Segment Analysis instance related report
      description: Retrieve details about customer segment analysis activity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRCustomerSegmentAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Customer Segment Analysis Instance
          schema:
            $ref: '#/definitions/CRCustomerSegmentAnalysisRetrieveOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateCustomerSegmentAnalysisPerformanceAnalysis
      summary: Details of a new PerformanceAnalysis instance
      description: Evaluate customer segment performance using a specific type of analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Customer Segment Analysis Request Payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of Customer Segment Analysis instance
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisEvaluateOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateCustomerSegmentAnalysisPerformanceAnalysis
      summary: Update to any amendable fields of the PerformanceAnalysis instance
      description: Update details of a specific customer segment performance analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis Request Payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated PerformanceAnalysis Instance
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisUpdateOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeCustomerSegmentAnalysisPerformanceAnalysisUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject, verify, etc. customer segment analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExchangeInputModel'
      responses:
        200:
          description: Successful exchange of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExchangeOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCustomerSegmentAnalysisPerformanceAnalysisUpdate
      summary: Invoke an automated execute action against the PerformanceAnalysis instance
      description: Execute an automated action against on-going analysis (e.g. refresh source production data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExecuteOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCustomerSegmentAnalysisPerformanceAnalysisUpdate
      summary: Invoke a service request action against the PerformanceAnalysis instance
      description: Request manual intervention to on-going analysis (e.g. amend analysis scope/approach)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRequestOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveCustomerSegmentAnalysisPerformanceAnalysis
      summary: Invoke a reporting action to obtain a PerformanceAnalysis instance related report.
      description: Retrieve details about a specific customer segment performance analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQPerformanceAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRetrieveOutputModel'
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerPortfolioReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- CustomerPortfolio Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /customer-portfolio/customer-segment-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerPortfolioBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'PerformanceAnalysis', ]
  /customer-portfolio/{sd-reference-id}/customer-segment-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCustomerPortfolioBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Customer Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Customer Segment Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- PerformanceAnalysis
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PerformanceAnalysis Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [PerformanceAnalysisID1, PerformanceAnalysisID2]
