grep date: ACHFulfillmentModel.yaml|grep -v -i update>>do
grep date: AccountRecoveryModel.yaml|grep -v -i update>>do
grep date: CardCaseModel.yaml|grep -v -i update>>do
grep date: CardCollectionsModel.yaml|grep -v -i update>>do
grep date: CardECommerceGatewayModel.yaml|grep -v -i update>>do
grep date: CardNetworkParticipantFacilityModel.yaml|grep -v -i update>>do
grep date: CardTerminalAdministrationModel.yaml|grep -v -i update>>do
grep date: ChannelActivityHistoryModel.yaml|grep -v -i update>>do
grep date: CollateralAllocationManagementModel.yaml|grep -v -i update>>do
grep date: CollateralAssetAdministrationModel.yaml|grep -v -i update>>do
grep date: ConsumerLoanModel.yaml|grep -v -i update>>do
grep date: CorporateDepositsModel.yaml|grep -v -i update>>do
grep date: CorporateTreasuryModel.yaml|grep -v -i update>>do
grep date: CorrespondenceModel.yaml|grep -v -i update>>do
grep date: CorrespondentBankModel.yaml|grep -v -i update>>do
grep date: CreditChargeCardModel.yaml|grep -v -i update>>do
grep date: CreditManagementModel.yaml|grep -v -i update>>do
grep date: CurrentAccountModel.yaml|grep -v -i update>>do
grep date: CustomerAccessEntitlementModel.yaml|grep -v -i update>>do
grep date: CustomerAgreementModel.yaml|grep -v -i update>>do
grep date: CustomerBehavioralInsightsModel.yaml|grep -v -i update>>do
grep date: CustomerBillingModel.yaml|grep -v -i update>>do
grep date: CustomerCaseModel.yaml|grep -v -i update>>do
grep date: CustomerCreditRatingModel.yaml|grep -v -i update>>do
grep date: CustomerPositionModel.yaml|grep -v -i update>>do
grep date: CustomerProductServiceEligibilityModel.yaml|grep -v -i update>>do
grep date: CustomerProfileModel.yaml|grep -v -i update>>do
grep date: CustomerReferenceDataManagementModel.yaml|grep -v -i update>>do
grep date: CustomerRelationshipManagementModel.yaml|grep -v -i update>>do
grep date: CustomerWorkbenchModel.yaml|grep -v -i update>>do
grep date: DelinquentAccountHandlingModel.yaml|grep -v -i update>>do
grep date: DepositAccountModel.yaml|grep -v -i update>>do
grep date: DisbursementModel.yaml|grep -v -i update>>do
grep date: DocumentServicesModel.yaml|grep -v -i update>>do
grep date: ECommerceGatewayBaseModel.yaml|grep -v -i update>>do
grep date: ECommerceGatewayModel.yaml|grep -v -i update>>do
grep date: ECommerceGatewayWithIdRootModel.yaml|grep -v -i update>>do
grep date: FinancialAccountingModel.yaml|grep -v -i update>>do
grep date: FinancialGatewayModel.yaml|grep -v -i update>>do
grep date: FraudResolutionModel.yaml|grep -v -i update>>do
grep date: IssuedDeviceAdministrationModel.yaml|grep -v -i update>>do
grep date: IssuedDeviceTrackingModel.yaml|grep -v -i update>>do
grep date: LocationDataManagementModel.yaml|grep -v -i update>>do
grep date: MerchantAcquiringFacilityModel.yaml|grep -v -i update>>do
grep date: OpenItemManagementModel.yaml|grep -v -i update>>do
grep date: PartModel.yaml|grep -v -i update>>do
grep date: PartyAuthenticationModel.yaml|grep -v -i update>>do
grep date: PartyDataManagementModel.yaml|grep -v -i update>>do
grep date: PartyLifeCycleManagementModel.yaml|grep -v -i update>>do
grep date: PaymentExecutionModel.yaml|grep -v -i update>>do
grep date: PaymentInitiationModel.yaml|grep -v -i update>>do
grep date: PaymentOrderModel.yaml|grep -v -i update>>do
grep date: PositionKeepingModel.yaml|grep -v -i update>>do
grep date: PositionManagementModel.yaml|grep -v -i update>>do
grep date: ProductBrokerAgreementModel.yaml|grep -v -i update>>do
grep date: SalesProductAgreementModel.yaml|grep -v -i update>>do
grep date: SavingsAccountModel.yaml|grep -v -i update>>do
grep date: ServicingMandateModel.yaml|grep -v -i update>>do
