swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Direct Debit Mandate'
 description: >

    ## Executive Summary:

    This service domains manages the customer mandates associated with direct debit processing for a corporate client

    ## Example of Use:

    A customer completes a direct debit mandate for a corporate client that is registered

    ## Description:

    Customer mandates are administered/managed that are associated with a direct debit processing facility provided for a corporate client. The individual customer mandates are registered and may be updated/amended. The mandates are referenced to confirm coverage when direct debit processing is undertaken periodically

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-direct-debit-mandate/1.0.0
schemes:
 - https
paths:
  /direct-debit-mandate/activation:
    post:
      tags:
      - activate
      operationId: activateSDDirectDebitMandate
      summary: Activate  a SDDirectDebitMandate servicing session
      description: Activate  a  SDDirectDebitMandate servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDDirectDebitMandate Request Payload
        schema:
          $ref: '#/definitions/SDDirectDebitMandateActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDDirectDebitMandateActivateOutputModel'
  /direct-debit-mandate/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDDirectDebitMandate
      summary: Update an active SDDirectDebitMandate session configuration
      description: Update an active SDDirectDebitMandate session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDirectDebitMandate Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDDirectDebitMandate Configure Request Payload
        schema:
          $ref: '#/definitions/SDDirectDebitMandateConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDDirectDebitMandateConfigureOutputModel'
  /direct-debit-mandate/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDDirectDebitMandate
      summary: "Capturing feedback against the SDDirectDebitMandate service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDDirectDebitMandate service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDirectDebitMandate Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDDirectDebitMandate Feedback Request Payload
        schema:
          $ref: '#/definitions/SDDirectDebitMandateFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDDirectDebitMandateFeedbackOutputModel'
  /direct-debit-mandate/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDDirectDebitMandate
      summary: Analytical views maintained by the SDDirectDebitMandate service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDDirectDebitMandate service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDirectDebitMandate Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDDirectDebitMandateRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDDirectDebitMandateRetrieveOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/registration:
    post:
      tags:
      - register
      operationId: registerDirectDebitMandateDirectoryEntry
      summary: Details of a new DirectDebitMandateDirectoryEntry instance
      description: Register a new direct debit (DD) mandate collection for a corporate customer
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: DirectDebitMandateDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryRegisterInputModel'
      responses:
        201:
          description: Successful registration of new DirectDebitMandateDirectoryEntry instance
          schema:
            $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryRegisterOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateDirectDebitMandateDirectoryEntry
      summary: Update to any amendable fields of the DirectDebitMandateDirectoryEntry instance
      description: Update details of an existing collection of DD mandates maintained for a corporate customer
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Direct Debit Mandate Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Direct Debit Mandate Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryUpdateOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlDirectDebitMandateDirectoryEntryUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control a direct debit mandate collection (e.g. suspend)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Direct Debit Mandate Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryControlInputModel'
      responses:
        200:
          description: Successful control of Direct Debit Mandate Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryControlOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveDirectDebitMandate
      summary: Invoke a reporting action to obtain a Direct Debit Mandate Directory Entry instance related report
      description: Retrieve details about a collection of DD mandates
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRDirectDebitMandateDirectoryEntryRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Direct Debit Mandate Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDirectDebitMandateDirectoryEntryRetrieveOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/registration:
    post:
      tags:
      - register
      operationId: registerDirectDebitMandateDirectoryEntryMandateRegistration
      summary: Details of a new MandateRegistration instance
      description: Register a customer's DD mandate for a corporate customer
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Direct Debit Mandate Directory Entry Request Payload
        schema:
          $ref: '#/definitions/BQMandateRegistrationRegisterInputModel'
      responses:
        201:
          description: Successful registration of Direct Debit Mandate Directory Entry instance
          schema:
            $ref: '#/definitions/BQMandateRegistrationRegisterOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateDirectDebitMandateDirectoryEntryMandateRegistration
      summary: Update to any amendable fields of the MandateRegistration instance
      description: Update details of the customer's DD mandate
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: MandateRegistration Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: MandateRegistration Request Payload
        schema:
          $ref: '#/definitions/BQMandateRegistrationUpdateInputModel'
      responses:
        200:
          description: Successfully Updated MandateRegistration Instance
          schema:
            $ref: '#/definitions/BQMandateRegistrationUpdateOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeDirectDebitMandateDirectoryEntryMandateRegistrationUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify etc. a customer's DD mandate
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: MandateRegistration Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: MandateRegistration request payload
        schema:
          $ref: '#/definitions/BQMandateRegistrationExchangeInputModel'
      responses:
        200:
          description: Successful exchange of MandateRegistration Instance Record
          schema:
            $ref: '#/definitions/BQMandateRegistrationExchangeOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeDirectDebitMandateDirectoryEntryMandateRegistrationUpdate
      summary: Invoke an automated execute action against the MandateRegistration instance
      description: Execute an automated action against the DD Mandate (e.g. test proposed payment)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: MandateRegistration Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: MandateRegistration request payload
        schema:
          $ref: '#/definitions/BQMandateRegistrationExecuteInputModel'
      responses:
        200:
          description: Successful execution of MandateRegistration Instance Record
          schema:
            $ref: '#/definitions/BQMandateRegistrationExecuteOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestDirectDebitMandateDirectoryEntryMandateRegistrationUpdate
      summary: Invoke a service request action against the MandateRegistration instance
      description: Request intervention with a customer's DD Mandate (e.g. retrieve paperwork)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: MandateRegistration Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: MandateRegistration request payload
        schema:
          $ref: '#/definitions/BQMandateRegistrationRequestInputModel'
      responses:
        200:
          description: Successful requisition of MandateRegistration Instance Record
          schema:
            $ref: '#/definitions/BQMandateRegistrationRequestOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/mandateregistration/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveDirectDebitMandateDirectoryEntryMandateRegistration
      summary: Invoke a reporting action to obtain a MandateRegistration instance related report.
      description: Retrieve details about a customer's DD mandate .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: MandateRegistration Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQMandateRegistrationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved MandateRegistration Instance Record
          schema:
            $ref: '#/definitions/BQMandateRegistrationRetrieveOutputModel'
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry:
    get:
      tags:
      - retrieve
      operationId: RetrieveDirectDebitMandateReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- DirectDebitMandate Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /direct-debit-mandate/direct-debit-mandate-directory-entry/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveDirectDebitMandateBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'MandateRegistration', ]
  /direct-debit-mandate/{sd-reference-id}/direct-debit-mandate-directory-entry/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveDirectDebitMandateBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Direct Debit Mandate Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Direct Debit Mandate Directory Entry Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- MandateRegistration
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- MandateRegistration Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [MandateRegistrationID1, MandateRegistrationID2]
