swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Document Services'
 description: >

    ## Executive Summary:

    This service domain captures, classifies, stores, maintains and retrieves any material document in any media as appropriate. It includes both electronic and physical distribution services

    ## Example of Use:

    A legal significant document is created during product fulfillment. It is classified and stored for subsequent reference as may be required

    ## Description:

    This service domain handles the status tracking, classification, recording/copying (for all media) storage and retrieval of all active documents of significance. It can include document services that retrieve documents from external sources on request. This can combine physical but more commonly electronic storage, retrieval and distribution of important and/or legally significant documentation. It delegates to the service domain Archive Services for longer term storage needs

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-document-services/1.0.0
schemes:
 - https
paths:
  /document-services/activation:
    post:
      tags:
      - activate
      operationId: activateSDDocumentServices
      summary: Activate  a SDDocumentServices servicing session
      description: Activate  a  SDDocumentServices servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDDocumentServices Request Payload
        schema:
          $ref: '#/definitions/SDDocumentServicesActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDDocumentServicesActivateOutputModel'
  /document-services/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDDocumentServices
      summary: Update an active SDDocumentServices session configuration
      description: Update an active SDDocumentServices session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDocumentServices Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDDocumentServices Configure Request Payload
        schema:
          $ref: '#/definitions/SDDocumentServicesConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDDocumentServicesConfigureOutputModel'
  /document-services/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDDocumentServices
      summary: "Capturing feedback against the SDDocumentServices service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDDocumentServices service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDocumentServices Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDDocumentServices Feedback Request Payload
        schema:
          $ref: '#/definitions/SDDocumentServicesFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDDocumentServicesFeedbackOutputModel'
  /document-services/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDDocumentServices
      summary: Analytical views maintained by the SDDocumentServices service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDDocumentServices service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDDocumentServices Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDDocumentServicesRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDDocumentServicesRetrieveOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/registration:
    post:
      tags:
      - register
      operationId: registerDocumentDirectoryEntry
      summary: Details of a new DocumentDirectoryEntry instance
      description: Register a document in the central catalog
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: DocumentDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRDocumentDirectoryEntryRegisterInputModel'
      responses:
        201:
          description: Successful registration of new DocumentDirectoryEntry instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryRegisterOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateDocumentDirectoryEntry
      summary: Update to any amendable fields of the DocumentDirectoryEntry instance
      description: Update details about a document in the catalog
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Document Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDocumentDirectoryEntryUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Document Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryUpdateOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlDocumentDirectoryEntryUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the processing of the directory entry (e.g. suspend)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Document Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDocumentDirectoryEntryControlInputModel'
      responses:
        200:
          description: Successful control of Document Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryControlOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeDocumentDirectoryEntryUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify, confirm details about a directory entry
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Document Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDocumentDirectoryEntryExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Document Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryExchangeOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestDocumentDirectoryEntryUpdate
      summary: Invoke a service request action against the DocumentDirectoryEntry instance
      description: Request provisioning of a document (from arranging initial capture to subsequent access)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Document Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRDocumentDirectoryEntryRequestInputModel'
      responses:
        200:
          description: Successful requisition of Document Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryRequestOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveDocumentServices
      summary: Invoke a reporting action to obtain a Document Directory Entry instance related report
      description: Retrieve details about a document
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRDocumentDirectoryEntryRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Document Directory Entry Instance
          schema:
            $ref: '#/definitions/CRDocumentDirectoryEntryRetrieveOutputModel'
  /document-services/{sd-reference-id}/document-directory-entry:
    get:
      tags:
      - retrieve
      operationId: RetrieveDocumentServicesReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- DocumentServices Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /document-services/document-directory-entry/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveDocumentServicesBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /document-services/{sd-reference-id}/document-directory-entry/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveDocumentServicesBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Document Services Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Document Directory Entry Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
