swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - E-Branch Operations'
 description: >

    ## Executive Summary:

    This service domain operates the bank's on-line web based electronic branch capabilities - controlling access and load balancing across available communications and processing resources to optimize performance/availability

    ## Example of Use:

    customers and non-bank customers browse the products and services available at the bank

    ## Description:

    This service domain operates the E-branch production systems conforming to planned service schedules. It handles customer and non-customer access checks, performs device load balancing and device failure and recovery handling - typically supporting a high performance 24/7 operation. It can include the integration of computer telephony integration (CTI) with branch and call center channels

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-e-branch-operations/1.0.0
schemes:
 - https
paths:
  /e-branch-operations/activation:
    post:
      tags:
      - activate
      operationId: activateSDEBranchOperations
      summary: Activate  a SDEBranchOperations servicing session
      description: Activate  a  SDEBranchOperations servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDEBranchOperations Request Payload
        schema:
          $ref: '#/definitions/SDEBranchOperationsActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDEBranchOperationsActivateOutputModel'
  /e-branch-operations/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDEBranchOperations
      summary: Update an active SDEBranchOperations session configuration
      description: Update an active SDEBranchOperations session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDEBranchOperations Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDEBranchOperations Configure Request Payload
        schema:
          $ref: '#/definitions/SDEBranchOperationsConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDEBranchOperationsConfigureOutputModel'
  /e-branch-operations/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDEBranchOperations
      summary: "Capturing feedback against the SDEBranchOperations service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDEBranchOperations service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDEBranchOperations Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDEBranchOperations Feedback Request Payload
        schema:
          $ref: '#/definitions/SDEBranchOperationsFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDEBranchOperationsFeedbackOutputModel'
  /e-branch-operations/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDEBranchOperations
      summary: Analytical views maintained by the SDEBranchOperations service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDEBranchOperations service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDEBranchOperations Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDEBranchOperationsRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDEBranchOperationsRetrieveOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/initiation:
    post:
      tags:
      - initiate
      operationId: initiateEBranchChannelOperatingSession
      summary: Details of a new EBranchChannelOperatingSession instance
      description: Initiate the eBranch channel service
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranchChannelOperatingSession Request Payload
        schema:
          $ref: '#/definitions/CREBranchChannelOperatingSessionInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new EBranchChannelOperatingSession instance
          schema:
            $ref: '#/definitions/CREBranchChannelOperatingSessionInitiateOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateEBranchChannelOperatingSession
      summary: Update to any amendable fields of the EBranchChannelOperatingSession instance
      description: Update the eBranch access service menu during the session (e.g. to notify customers of an issue)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranch Channel Operating Session Request Payload
        schema:
          $ref: '#/definitions/CREBranchChannelOperatingSessionUpdateInputModel'
      responses:
        200:
          description: Successfully Updated EBranch Channel Operating Session Instance
          schema:
            $ref: '#/definitions/CREBranchChannelOperatingSessionUpdateOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlEBranchChannelOperatingSessionUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the service session (e.g. terminate)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranch Channel Operating Session Request Payload
        schema:
          $ref: '#/definitions/CREBranchChannelOperatingSessionControlInputModel'
      responses:
        200:
          description: Successful control of EBranch Channel Operating Session Instance
          schema:
            $ref: '#/definitions/CREBranchChannelOperatingSessionControlOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestEBranchChannelOperatingSessionUpdate
      summary: Invoke a service request action against the EBranchChannelOperatingSession instance
      description: Report an issue with the production service
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranch Channel Operating Session Request Payload
        schema:
          $ref: '#/definitions/CREBranchChannelOperatingSessionRequestInputModel'
      responses:
        200:
          description: Successful requisition of EBranch Channel Operating Session Instance
          schema:
            $ref: '#/definitions/CREBranchChannelOperatingSessionRequestOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveE-BranchOperations
      summary: Invoke a reporting action to obtain a EBranch Channel Operating Session instance related report
      description: Retrieve details and statistics relating to a session
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CREBranchChannelOperatingSessionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved EBranch Channel Operating Session Instance
          schema:
            $ref: '#/definitions/CREBranchChannelOperatingSessionRetrieveOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/inbound/initiation:
    post:
      tags:
      - initiate
      operationId: initiateEBranchChannelOperatingSessionInbound
      summary: Details of a new Inbound instance
      description: Initiate an inbound eBranch connection
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranch Channel Operating Session Request Payload
        schema:
          $ref: '#/definitions/BQInboundInitiateInputModel'
      responses:
        201:
          description: Successful initiation of EBranch Channel Operating Session instance
          schema:
            $ref: '#/definitions/BQInboundInitiateOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/inbound/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveEBranchChannelOperatingSessionInbound
      summary: Invoke a reporting action to obtain a Inbound instance related report.
      description: Retrieve details about an inbound eBranch connection .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Inbound Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQInboundRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Inbound Instance Record
          schema:
            $ref: '#/definitions/BQInboundRetrieveOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/outbound/initiation:
    post:
      tags:
      - initiate
      operationId: initiateEBranchChannelOperatingSessionOutbound
      summary: Details of a new Outbound instance
      description: Initiate an outbound eBranch connection
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: EBranch Channel Operating Session Request Payload
        schema:
          $ref: '#/definitions/BQOutboundInitiateInputModel'
      responses:
        201:
          description: Successful initiation of EBranch Channel Operating Session instance
          schema:
            $ref: '#/definitions/BQOutboundInitiateOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/outbound/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveEBranchChannelOperatingSessionOutbound
      summary: Invoke a reporting action to obtain a Outbound instance related report.
      description: Retrieve details about an outbound eBranch connection .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Outbound Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQOutboundRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Outbound Instance Record
          schema:
            $ref: '#/definitions/BQOutboundRetrieveOutputModel'
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session:
    get:
      tags:
      - retrieve
      operationId: RetrieveE-BranchOperationsReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- EBranchOperations Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /e-branch-operations/ebranch-channel-operating-session/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveE-BranchOperationsBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Inbound',  'Outbound', ]
  /e-branch-operations/{sd-reference-id}/ebranch-channel-operating-session/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveE-BranchOperationsBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: E-Branch Operations Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: EBranch Channel Operating Session Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Outbound
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Outbound Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [OutboundID1, OutboundID2]
