swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Financial Market Research'
 description: >

    ## Executive Summary:

    The service domain consolidates external financial market research

    ## Example of Use:

    Example of Use:An investment portfolio manager obtains financial market research to support portfolio rebalancing decisions

    ## Description:

    Consolidate financial market information from a variety of sources and optionally organize the consolidated information to align to different topics or categories for subsequent selection and analysis (see Financial Market Analysis)

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-financial-market-research/1.0.0
schemes:
 - https
paths:
  /financial-market-research/activation:
    post:
      tags:
      - activate
      operationId: activateSDFinancialMarketResearch
      summary: Activate  a SDFinancialMarketResearch servicing session
      description: Activate  a  SDFinancialMarketResearch servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDFinancialMarketResearch Request Payload
        schema:
          $ref: '#/definitions/SDFinancialMarketResearchActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDFinancialMarketResearchActivateOutputModel'
  /financial-market-research/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDFinancialMarketResearch
      summary: Update an active SDFinancialMarketResearch session configuration
      description: Update an active SDFinancialMarketResearch session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialMarketResearch Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFinancialMarketResearch Configure Request Payload
        schema:
          $ref: '#/definitions/SDFinancialMarketResearchConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDFinancialMarketResearchConfigureOutputModel'
  /financial-market-research/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDFinancialMarketResearch
      summary: "Capturing feedback against the SDFinancialMarketResearch service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDFinancialMarketResearch service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialMarketResearch Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFinancialMarketResearch Feedback Request Payload
        schema:
          $ref: '#/definitions/SDFinancialMarketResearchFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDFinancialMarketResearchFeedbackOutputModel'
  /financial-market-research/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDFinancialMarketResearch
      summary: Analytical views maintained by the SDFinancialMarketResearch service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDFinancialMarketResearch service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialMarketResearch Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDFinancialMarketResearchRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDFinancialMarketResearchRetrieveOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/registration:
    post:
      tags:
      - register
      operationId: registerFinancialMarketResearchDirectoryEntry
      summary: Details of a new FinancialMarketResearchDirectoryEntry instance
      description: Register or establish a financial market research viewpoint
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FinancialMarketResearchDirectoryEntry Request Payload
        schema:
          $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryRegisterInputModel'
      responses:
        201:
          description: Successful registration of new FinancialMarketResearchDirectoryEntry instance
          schema:
            $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryRegisterOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialMarketResearchDirectoryEntry
      summary: Update to any amendable fields of the FinancialMarketResearchDirectoryEntry instance
      description: Update the details or make-up of a financial market research viewpoint
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Market Research Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Market Research Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Financial Market Research Directory Entry Instance
          schema:
            $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryUpdateOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeFinancialMarketResearchDirectoryEntryUpdate
      summary: Invoke an automated execute action against the FinancialMarketResearchDirectoryEntry instance
      description: Automatically extract details of a maintained financial market research viewpoint
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Market Research Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Market Research Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryExecuteInputModel'
      responses:
        200:
          description: Successful execution of Financial Market Research Directory Entry Instance
          schema:
            $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryExecuteOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFinancialMarketResearchDirectoryEntryUpdate
      summary: Invoke a service request action against the FinancialMarketResearchDirectoryEntry instance
      description: Request a viewpoint is refreshed or adjusted in some manner
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Market Research Directory Entry Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Market Research Directory Entry Request Payload
        schema:
          $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryRequestInputModel'
      responses:
        200:
          description: Successful requisition of Financial Market Research Directory Entry Instance
          schema:
            $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryRequestOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialMarketResearch
      summary: Invoke a reporting action to obtain a Financial Market Research Directory Entry instance related report
      description: Retrieve details about and the content of a maintained financial market research viewpoint
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Market Research Directory Entry Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFinancialMarketResearchDirectoryEntryRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Financial Market Research Directory Entry Instance
          schema:
            $ref: '#/definitions/CRFinancialMarketResearchDirectoryEntryRetrieveOutputModel'
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialMarketResearchReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- FinancialMarketResearch Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /financial-market-research/financial-market-research-directory-entry/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialMarketResearchBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /financial-market-research/{sd-reference-id}/financial-market-research-directory-entry/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialMarketResearchBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Market Research Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Market Research Directory Entry Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
