swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Financial Gateway'
 description: >

    ## Executive Summary:

    This service domain operates automated message interfaces to secure networks such as SWIFT, TELEX, ACH and Financial Market/Exchange reporting services

    ## Example of Use:

    During the 24 hour cycle, the bank's 'wire room' unit establishes the connections with the different payments, SWIFT and reporting networks

    ## Description:

    This service domain supports the operational connections with the range of financial networks that support interbank and financial institution connectivity. This includes SWIFT, ACH gateways, and market exchange/regulatory reporting connections. The service domain does not create content itself, it provides a message exchange service between (financial) institutions for various units within the bank. It may format messages and maintain and apply authentication and encryption keys to the transmitted messages and necessary. It also provides operational message recovery and retransmission facilities as appropriate

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-financial-gateway/1.0.0
schemes:
 - https
paths:
  /financial-gateway/activation:
    post:
      tags:
      - activate
      operationId: activateSDFinancialGateway
      summary: Activate  a SDFinancialGateway servicing session
      description: Activate  a  SDFinancialGateway servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDFinancialGateway Request Payload
        schema:
          $ref: '#/definitions/SDFinancialGatewayActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDFinancialGatewayActivateOutputModel'
  /financial-gateway/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDFinancialGateway
      summary: Update an active SDFinancialGateway session configuration
      description: Update an active SDFinancialGateway session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialGateway Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFinancialGateway Configure Request Payload
        schema:
          $ref: '#/definitions/SDFinancialGatewayConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDFinancialGatewayConfigureOutputModel'
  /financial-gateway/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDFinancialGateway
      summary: "Capturing feedback against the SDFinancialGateway service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDFinancialGateway service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialGateway Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFinancialGateway Feedback Request Payload
        schema:
          $ref: '#/definitions/SDFinancialGatewayFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDFinancialGatewayFeedbackOutputModel'
  /financial-gateway/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDFinancialGateway
      summary: Analytical views maintained by the SDFinancialGateway service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDFinancialGateway service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFinancialGateway Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDFinancialGatewayRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDFinancialGatewayRetrieveOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialGatewayOperatingSession
      summary: Details of a new FinancialGatewayOperatingSession instance
      description: Initiate the financial gateway service session
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FinancialGatewayOperatingSession Request Payload
        schema:
          $ref: '#/definitions/CRFinancialGatewayOperatingSessionInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new FinancialGatewayOperatingSession instance
          schema:
            $ref: '#/definitions/CRFinancialGatewayOperatingSessionInitiateOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialGatewayOperatingSession
      summary: Update to any amendable fields of the FinancialGatewayOperatingSession instance
      description: Update the gateway service details
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Gateway Operating Session Request Payload
        schema:
          $ref: '#/definitions/CRFinancialGatewayOperatingSessionUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Financial Gateway Operating Session Instance
          schema:
            $ref: '#/definitions/CRFinancialGatewayOperatingSessionUpdateOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlFinancialGatewayOperatingSessionUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the service session (e.g. terminate)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Gateway Operating Session Request Payload
        schema:
          $ref: '#/definitions/CRFinancialGatewayOperatingSessionControlInputModel'
      responses:
        200:
          description: Successful control of Financial Gateway Operating Session Instance
          schema:
            $ref: '#/definitions/CRFinancialGatewayOperatingSessionControlOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFinancialGatewayOperatingSessionUpdate
      summary: Invoke a service request action against the FinancialGatewayOperatingSession instance
      description: Report an issue with the production service
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Gateway Operating Session Request Payload
        schema:
          $ref: '#/definitions/CRFinancialGatewayOperatingSessionRequestInputModel'
      responses:
        200:
          description: Successful requisition of Financial Gateway Operating Session Instance
          schema:
            $ref: '#/definitions/CRFinancialGatewayOperatingSessionRequestOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialGateway
      summary: Invoke a reporting action to obtain a Financial Gateway Operating Session instance related report
      description: Retrieve details and statistics relating to a session
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFinancialGatewayOperatingSessionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Financial Gateway Operating Session Instance
          schema:
            $ref: '#/definitions/CRFinancialGatewayOperatingSessionRetrieveOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/inbound/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialGatewayOperatingSessionInbound
      summary: Details of a new Inbound instance
      description: Initiate inbound financial message handling
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Gateway Operating Session Request Payload
        schema:
          $ref: '#/definitions/BQInboundInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Financial Gateway Operating Session instance
          schema:
            $ref: '#/definitions/BQInboundInitiateOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/inbound/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialGatewayOperatingSessionInbound
      summary: Invoke a reporting action to obtain a Inbound instance related report.
      description: Retrieve details about an inbound financial message .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Inbound Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQInboundRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Inbound Instance Record
          schema:
            $ref: '#/definitions/BQInboundRetrieveOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/outbound/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialGatewayOperatingSessionOutbound
      summary: Details of a new Outbound instance
      description: Initiate outbound financial message handling
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Gateway Operating Session Request Payload
        schema:
          $ref: '#/definitions/BQOutboundInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Financial Gateway Operating Session instance
          schema:
            $ref: '#/definitions/BQOutboundInitiateOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/outbound/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialGatewayOperatingSessionOutbound
      summary: Invoke a reporting action to obtain a Outbound instance related report.
      description: Retrieve details about an outbound financial message .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Outbound Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQOutboundRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Outbound Instance Record
          schema:
            $ref: '#/definitions/BQOutboundRetrieveOutputModel'
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialGatewayReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- FinancialGateway Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /financial-gateway/financial-gateway-operating-session/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialGatewayBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Inbound',  'Outbound', ]
  /financial-gateway/{sd-reference-id}/financial-gateway-operating-session/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFinancialGatewayBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Financial Gateway Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Gateway Operating Session Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Outbound
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Outbound Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [OutboundID1, OutboundID2]
