swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Fraud Evaluation'
 description: >

    ## Executive Summary:

    The service domain executes fraud behavioral pattern tests to detect possible fraudulent transactions/activity

    ## Example of Use:

    Example of use:Card transactions are subjected to an array of fraud pattern test to detect 'out of pattern' behavior - anomalies are highlighted for analysis

    ## Description:

    This service domain handles the structured execution of fraud detection tests/routines that are used to identify possible fraud by detecting out of pattern behaviors. The tests may run in-line with production or may access transaction logs as appropriate. Detected anomalies are passed for further analysis and resolution.

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-fraud-evaluation/1.0.0
schemes:
 - https
paths:
  /fraud-evaluation/activation:
    post:
      tags:
      - activate
      operationId: activateSDFraudEvaluation
      summary: Activate  a SDFraudEvaluation servicing session
      description: Activate  a  SDFraudEvaluation servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDFraudEvaluation Request Payload
        schema:
          $ref: '#/definitions/SDFraudEvaluationActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDFraudEvaluationActivateOutputModel'
  /fraud-evaluation/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDFraudEvaluation
      summary: Update an active SDFraudEvaluation session configuration
      description: Update an active SDFraudEvaluation session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudEvaluation Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudEvaluation Configure Request Payload
        schema:
          $ref: '#/definitions/SDFraudEvaluationConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDFraudEvaluationConfigureOutputModel'
  /fraud-evaluation/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDFraudEvaluation
      summary: "Capturing feedback against the SDFraudEvaluation service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDFraudEvaluation service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudEvaluation Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudEvaluation Feedback Request Payload
        schema:
          $ref: '#/definitions/SDFraudEvaluationFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDFraudEvaluationFeedbackOutputModel'
  /fraud-evaluation/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDFraudEvaluation
      summary: Analytical views maintained by the SDFraudEvaluation service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDFraudEvaluation service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudEvaluation Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDFraudEvaluationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDFraudEvaluationRetrieveOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateFraudEvaluationAssessment
      summary: Details of a new FraudEvaluationAssessment instance
      description: Start a fraud evaluation for a production transaction set
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FraudEvaluationAssessment Request Payload
        schema:
          $ref: '#/definitions/CRFraudEvaluationAssessmentEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new FraudEvaluationAssessment instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentEvaluateOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeFraudEvaluationAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify, reject a fraud evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Evaluation Assessment Request Payload
        schema:
          $ref: '#/definitions/CRFraudEvaluationAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Fraud Evaluation Assessment Instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentExchangeOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeFraudEvaluationAssessmentUpdate
      summary: Invoke an automated execute action against the FraudEvaluationAssessment instance
      description: Perform an automated action to an active evaluation (e.g. upload additional data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Evaluation Assessment Request Payload
        schema:
          $ref: '#/definitions/CRFraudEvaluationAssessmentExecuteInputModel'
      responses:
        200:
          description: Successful execution of Fraud Evaluation Assessment Instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentExecuteOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFraudEvaluationAssessmentUpdate
      summary: Invoke a service request action against the FraudEvaluationAssessment instance
      description: Request manual intervention to an active assessment (e.g. change test make-up)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Evaluation Assessment Request Payload
        schema:
          $ref: '#/definitions/CRFraudEvaluationAssessmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Fraud Evaluation Assessment Instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentRequestOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantFraudEvaluationAssessmentUpdate
      summary: Invoke a grant request action from the FraudEvaluationAssessment instance to obtain access permission
      description: Obtain permission to act on/apply the assessment (if appropriate)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Evaluation Assessment Request Payload
        schema:
          $ref: '#/definitions/CRFraudEvaluationAssessmentGrantInputModel'
      responses:
        200:
          description: Successful grant of Fraud Evaluation Assessment Instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentGrantOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudEvaluation
      summary: Invoke a reporting action to obtain a Fraud Evaluation Assessment instance related report
      description: Retrieve details about a fraud evaluation assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFraudEvaluationAssessmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Fraud Evaluation Assessment Instance
          schema:
            $ref: '#/definitions/CRFraudEvaluationAssessmentRetrieveOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/rulesetsanddecisiontrees/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudEvaluationAssessmentRuleSetsandDecisionTrees
      summary: Invoke a reporting action to obtain a RuleSetsandDecisionTrees instance related report.
      description: Retrieve details about an out of pattern test applied .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: RuleSetsandDecisionTrees Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQRuleSetsandDecisionTreesRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved RuleSetsandDecisionTrees Instance Record
          schema:
            $ref: '#/definitions/BQRuleSetsandDecisionTreesRetrieveOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/models/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudEvaluationAssessmentModels
      summary: Invoke a reporting action to obtain a Models instance related report.
      description: Retrieve details about a regression test applied .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Models Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQModelsRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Models Instance Record
          schema:
            $ref: '#/definitions/BQModelsRetrieveOutputModel'
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudEvaluationReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- FraudEvaluation Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /fraud-evaluation/fraud-evaluation-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudEvaluationBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'RuleSetsandDecisionTrees',  'Models', ]
  /fraud-evaluation/{sd-reference-id}/fraud-evaluation-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudEvaluationBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Evaluation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Evaluation Assessment Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Models
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Models Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ModelsID1, ModelsID2]
