swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Fraud Resolution'
 description: >

    ## Executive Summary:

    This service domain sets up and processes a fraud case resulting from fraud behavior that has been detected during production processing

    ## Example of Use:

    Example of use:A pattern of possible fraud is highlighted in transaction records that is researched and evidence of fraud discovered. Prosecution/resolution activity is initiated

    ## Description:

    Setup and update Fraud Case and handle investigation and resolution steps, which may involve initiating containment actions, obtaining documentation, performing forensic investigation and actions, determining liability, initiating resolution actions such as reversals and financial adjustments, subscribing and publishing to Consortia, determining root cause and initiating corrective/preventive actions. The Fraud Case may be opened by Product/Channel Facility, Fraud Diagnosis or by Customer Case.

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-fraud-resolution/1.0.0
schemes:
 - https
paths:
  /fraud-resolution/activation:
    post:
      tags:
      - activate
      operationId: activateSDFraudResolution
      summary: Activate  a SDFraudResolution servicing session
      description: Activate  a  SDFraudResolution servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDFraudResolution Request Payload
        schema:
          $ref: '#/definitions/SDFraudResolutionActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDFraudResolutionActivateOutputModel'
  /fraud-resolution/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDFraudResolution
      summary: Update an active SDFraudResolution session configuration
      description: Update an active SDFraudResolution session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudResolution Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudResolution Configure Request Payload
        schema:
          $ref: '#/definitions/SDFraudResolutionConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDFraudResolutionConfigureOutputModel'
  /fraud-resolution/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDFraudResolution
      summary: "Capturing feedback against the SDFraudResolution service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDFraudResolution service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudResolution Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudResolution Feedback Request Payload
        schema:
          $ref: '#/definitions/SDFraudResolutionFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDFraudResolutionFeedbackOutputModel'
  /fraud-resolution/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDFraudResolution
      summary: Analytical views maintained by the SDFraudResolution service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDFraudResolution service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudResolution Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDFraudResolutionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDFraudResolutionRetrieveOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFraudResolutionProcedure
      summary: Details of a new FraudResolutionProcedure instance
      description: Initiate a fraud case
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FraudResolutionProcedure Request Payload
        schema:
          $ref: '#/definitions/CRFraudResolutionProcedureInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new FraudResolutionProcedure instance
          schema:
            $ref: '#/definitions/CRFraudResolutionProcedureInitiateOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFraudResolutionProcedure
      summary: Update to any amendable fields of the FraudResolutionProcedure instance
      description: Update details of an active fraud case
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Resolution Procedure Request Payload
        schema:
          $ref: '#/definitions/CRFraudResolutionProcedureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Fraud Resolution Procedure Instance
          schema:
            $ref: '#/definitions/CRFraudResolutionProcedureUpdateOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeFraudResolutionProcedureUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept or reject recommendations coming from fraud resolution
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Resolution Procedure Request Payload
        schema:
          $ref: '#/definitions/CRFraudResolutionProcedureExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Fraud Resolution Procedure Instance
          schema:
            $ref: '#/definitions/CRFraudResolutionProcedureExchangeOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudResolution
      summary: Invoke a reporting action to obtain a Fraud Resolution Procedure instance related report
      description: Retrieve information about an active fraud case
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFraudResolutionProcedureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Fraud Resolution Procedure Instance
          schema:
            $ref: '#/definitions/CRFraudResolutionProcedureRetrieveOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/caseanalysis/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudResolutionProcedureCaseAnalysis
      summary: Invoke a reporting action to obtain a CaseAnalysis instance related report.
      description: Retrieve information about an active fraud case analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CaseAnalysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQCaseAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved CaseAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQCaseAnalysisRetrieveOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/casedetermination/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeFraudResolutionProcedureCaseDeterminationUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept or reject proposed determination
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CaseDetermination Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CaseDetermination request payload
        schema:
          $ref: '#/definitions/BQCaseDeterminationExchangeInputModel'
      responses:
        200:
          description: Successful exchange of CaseDetermination Instance Record
          schema:
            $ref: '#/definitions/BQCaseDeterminationExchangeOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/casedetermination/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudResolutionProcedureCaseDetermination
      summary: Invoke a reporting action to obtain a CaseDetermination instance related report.
      description: Retrieve information about an active fraud case determination .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CaseDetermination Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQCaseDeterminationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved CaseDetermination Instance Record
          schema:
            $ref: '#/definitions/BQCaseDeterminationRetrieveOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/caseresolution/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFraudResolutionProcedureCaseResolutionUpdate
      summary: Invoke a service request action against the CaseResolution instance
      description: Request reworking of resolution to a case
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CaseResolution Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CaseResolution request payload
        schema:
          $ref: '#/definitions/BQCaseResolutionRequestInputModel'
      responses:
        200:
          description: Successful requisition of CaseResolution Instance Record
          schema:
            $ref: '#/definitions/BQCaseResolutionRequestOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/caseresolution/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudResolutionProcedureCaseResolution
      summary: Invoke a reporting action to obtain a CaseResolution instance related report.
      description: Retrieve information about an active fraud case resolution .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CaseResolution Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQCaseResolutionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved CaseResolution Instance Record
          schema:
            $ref: '#/definitions/BQCaseResolutionRetrieveOutputModel'
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudResolutionReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- FraudResolution Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /fraud-resolution/fraud-resolution-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudResolutionBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'CaseAnalysis',  'CaseDetermination',  'CaseResolution', ]
  /fraud-resolution/{sd-reference-id}/fraud-resolution-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudResolutionBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Resolution Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Resolution Procedure Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- CaseResolution
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- CaseResolution Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [CaseResolutionID1, CaseResolutionID2]
