swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Fraud Diagnosis'
 description: >

    ## Executive Summary:

    This service domain handles the evaluation of detected possible fraud to support an appropriate response to contain the exposure

    ## Example of Use:

    Out of pattern card use is detected and the details passed for analysis. The analysis determines there is a high probability of fraud recommending appropriate containment actions

    ## Description:

    Analyze suspect transaction with Customer behavior information across product portfolio, using Expert Systems /Artificial Intelligence and/or manual review, including customer contact to determine if transaction is fraudulent. Further apply Economic Model to determine transaction disposition and notify applicable Product Fulfillment SDs.

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-fraud-diagnosis/1.0.0
schemes:
 - https
paths:
  /fraud-diagnosis/activation:
    post:
      tags:
      - activate
      operationId: activateSDFraudDiagnosis
      summary: Activate  a SDFraudDiagnosis servicing session
      description: Activate  a  SDFraudDiagnosis servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDFraudDiagnosis Request Payload
        schema:
          $ref: '#/definitions/SDFraudDiagnosisActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDFraudDiagnosisActivateOutputModel'
  /fraud-diagnosis/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDFraudDiagnosis
      summary: Update an active SDFraudDiagnosis session configuration
      description: Update an active SDFraudDiagnosis session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudDiagnosis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudDiagnosis Configure Request Payload
        schema:
          $ref: '#/definitions/SDFraudDiagnosisConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDFraudDiagnosisConfigureOutputModel'
  /fraud-diagnosis/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDFraudDiagnosis
      summary: "Capturing feedback against the SDFraudDiagnosis service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDFraudDiagnosis service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudDiagnosis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDFraudDiagnosis Feedback Request Payload
        schema:
          $ref: '#/definitions/SDFraudDiagnosisFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDFraudDiagnosisFeedbackOutputModel'
  /fraud-diagnosis/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDFraudDiagnosis
      summary: Analytical views maintained by the SDFraudDiagnosis service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDFraudDiagnosis service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDFraudDiagnosis Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDFraudDiagnosisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDFraudDiagnosisRetrieveOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateFraudDiagnosisAnalysis
      summary: Details of a new FraudDiagnosisAnalysis instance
      description: Start a fraud diagnosis evaluation on a transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FraudDiagnosisAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRFraudDiagnosisAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new FraudDiagnosisAnalysis instance
          schema:
            $ref: '#/definitions/CRFraudDiagnosisAnalysisEvaluateOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFraudDiagnosisAnalysis
      summary: Update to any amendable fields of the FraudDiagnosisAnalysis instance
      description: Update details for an active fraud diagnosis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Diagnosis Analysis Request Payload
        schema:
          $ref: '#/definitions/CRFraudDiagnosisAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Fraud Diagnosis Analysis Instance
          schema:
            $ref: '#/definitions/CRFraudDiagnosisAnalysisUpdateOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeFraudDiagnosisAnalysisUpdate
      summary: Invoke an automated execute action against the FraudDiagnosisAnalysis instance
      description: Perform an automated action to an active diagnosis (e.g. upload additional data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Diagnosis Analysis Request Payload
        schema:
          $ref: '#/definitions/CRFraudDiagnosisAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of Fraud Diagnosis Analysis Instance
          schema:
            $ref: '#/definitions/CRFraudDiagnosisAnalysisExecuteOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFraudDiagnosisAnalysisUpdate
      summary: Invoke a service request action against the FraudDiagnosisAnalysis instance
      description: Request manual intervention for an active diagnosis (e.g. request access to analyst)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Fraud Diagnosis Analysis Request Payload
        schema:
          $ref: '#/definitions/CRFraudDiagnosisAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Fraud Diagnosis Analysis Instance
          schema:
            $ref: '#/definitions/CRFraudDiagnosisAnalysisRequestOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudDiagnosis
      summary: Invoke a reporting action to obtain a Fraud Diagnosis Analysis instance related report
      description: Retrieve details about a fraud diagnosis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFraudDiagnosisAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Fraud Diagnosis Analysis Instance
          schema:
            $ref: '#/definitions/CRFraudDiagnosisAnalysisRetrieveOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/customerbehavior/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudDiagnosisAnalysisCustomerBehavior
      summary: Invoke a reporting action to obtain a CustomerBehavior instance related report.
      description: Retrieve details about a customer behavior analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: CustomerBehavior Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQCustomerBehaviorRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved CustomerBehavior Instance Record
          schema:
            $ref: '#/definitions/BQCustomerBehaviorRetrieveOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/economicmodel/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudDiagnosisAnalysisEconomicModel
      summary: Invoke a reporting action to obtain a EconomicModel instance related report.
      description: Retrieve details about an economic model analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: EconomicModel Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQEconomicModelRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved EconomicModel Instance Record
          schema:
            $ref: '#/definitions/BQEconomicModelRetrieveOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/analystreview/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestFraudDiagnosisAnalysisAnalystReviewUpdate
      summary: Invoke a service request action against the AnalystReview instance
      description: Request access to an analist for an active diagnosis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: AnalystReview Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: AnalystReview request payload
        schema:
          $ref: '#/definitions/BQAnalystReviewRequestInputModel'
      responses:
        200:
          description: Successful requisition of AnalystReview Instance Record
          schema:
            $ref: '#/definitions/BQAnalystReviewRequestOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/analystreview/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFraudDiagnosisAnalysisAnalystReview
      summary: Invoke a reporting action to obtain a AnalystReview instance related report.
      description: Retrieve details about a analyst review of a transaction .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: AnalystReview Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQAnalystReviewRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved AnalystReview Instance Record
          schema:
            $ref: '#/definitions/BQAnalystReviewRetrieveOutputModel'
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudDiagnosisReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- FraudDiagnosis Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /fraud-diagnosis/fraud-diagnosis-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudDiagnosisBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'CustomerBehavior',  'EconomicModel',  'AnalystReview', ]
  /fraud-diagnosis/{sd-reference-id}/fraud-diagnosis-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveFraudDiagnosisBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Fraud Diagnosis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Fraud Diagnosis Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- AnalystReview
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- AnalystReview Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [AnalystReviewID1, AnalystReviewID2]
