swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Guideline Compliance'
 description: >

    ## Executive Summary:

    This service domain develops and applies a portfolio of guideline compliance tests to confirm adherence to bank and regulator imposed internal procedures. Tests may be made on complete transaction data or a meaningful samples as appropriate to mitigate exposure to non-compliant behaviors. Compliance checks may be in response to a schedule, a specific request as part of normal processing or may be initiated randomly as an oversight activity

    ## Example of Use:

    A loan origination process is submitted for guideline compliance checks prior to completing the origination/loan closure process

    ## Description:

    This service center administers the activity of a specialists tasked with testing and confirming guideline compliance. Compliance tests may include document reviews, more detailed transaction analysis and may involve interactions with the unit under test to obtain additional detail/explanation. Guideline compliance is typically focused on larger value investment and loan activities, confirming transactions are executed in alignment with management guidelines and prudential policies.

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-guideline-compliance/1.0.0
schemes:
 - https
paths:
  /guideline-compliance/activation:
    post:
      tags:
      - activate
      operationId: activateSDGuidelineCompliance
      summary: Activate  a SDGuidelineCompliance servicing session
      description: Activate  a  SDGuidelineCompliance servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDGuidelineComplianceActivateOutputModel'
  /guideline-compliance/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDGuidelineCompliance
      summary: Update an active SDGuidelineCompliance session configuration
      description: Update an active SDGuidelineCompliance session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDGuidelineCompliance Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Configure Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDGuidelineComplianceConfigureOutputModel'
  /guideline-compliance/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDGuidelineCompliance
      summary: "Capturing feedback against the SDGuidelineCompliance service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDGuidelineCompliance service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDGuidelineCompliance Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Feedback Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDGuidelineComplianceFeedbackOutputModel'
  /guideline-compliance/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDGuidelineCompliance
      summary: Analytical views maintained by the SDGuidelineCompliance service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDGuidelineCompliance service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDGuidelineCompliance Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDGuidelineComplianceRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDGuidelineComplianceRetrieveOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateGuidelineComplianceAssessment
      summary: Details of a new GuidelineComplianceAssessment instance
      description: Start a guideline compliance evaluation assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: GuidelineComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new GuidelineComplianceAssessment instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentEvaluateOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateGuidelineComplianceAssessment
      summary: Update to any amendable fields of the GuidelineComplianceAssessment instance
      description: Update submitted details or content for an on-going guideline compliance assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Guideline Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Guideline Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentUpdateOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeGuidelineComplianceAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept or reject a guideline compliance determination
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Guideline Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Guideline Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentExchangeOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestGuidelineComplianceAssessmentUpdate
      summary: Invoke a service request action against the GuidelineComplianceAssessment instance
      description: Request a review or adjudication for a guideline assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Guideline Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Guideline Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentRequestOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveGuidelineCompliance
      summary: Invoke a reporting action to obtain a Guideline Compliance Assessment instance related report
      description: Retrieve details and content from an active guideline compliance assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRGuidelineComplianceAssessmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Guideline Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentRetrieveOutputModel'
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- GuidelineCompliance Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /guideline-compliance/guideline-compliance-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /guideline-compliance/{sd-reference-id}/guideline-compliance-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Guideline Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
