swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Investment Portfolio Analysis'
 description: >

    ## Executive Summary:

    Assess and report on investment portfolio make-up, valuation and performance

    ## Example of Use:

    Example of use:A relationship manager requests an investment portfolio performance analysis prior to a regular client meeting

    ## Description:

    Perform scheduled and ad-hoc performance analysis on a customer's investment portfolio. This can include different types of analysis and performance comparisons

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-investment-portfolio-analysis/1.0.0
schemes:
 - https
paths:
  /investment-portfolio-analysis/activation:
    post:
      tags:
      - activate
      operationId: activateSDInvestmentPortfolioAnalysis
      summary: Activate  a SDInvestmentPortfolioAnalysis servicing session
      description: Activate  a  SDInvestmentPortfolioAnalysis servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDInvestmentPortfolioAnalysis Request Payload
        schema:
          $ref: '#/definitions/SDInvestmentPortfolioAnalysisActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDInvestmentPortfolioAnalysisActivateOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDInvestmentPortfolioAnalysis
      summary: Update an active SDInvestmentPortfolioAnalysis session configuration
      description: Update an active SDInvestmentPortfolioAnalysis session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDInvestmentPortfolioAnalysis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDInvestmentPortfolioAnalysis Configure Request Payload
        schema:
          $ref: '#/definitions/SDInvestmentPortfolioAnalysisConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDInvestmentPortfolioAnalysisConfigureOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDInvestmentPortfolioAnalysis
      summary: "Capturing feedback against the SDInvestmentPortfolioAnalysis service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDInvestmentPortfolioAnalysis service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDInvestmentPortfolioAnalysis Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDInvestmentPortfolioAnalysis Feedback Request Payload
        schema:
          $ref: '#/definitions/SDInvestmentPortfolioAnalysisFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDInvestmentPortfolioAnalysisFeedbackOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDInvestmentPortfolioAnalysis
      summary: Analytical views maintained by the SDInvestmentPortfolioAnalysis service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDInvestmentPortfolioAnalysis service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDInvestmentPortfolioAnalysis Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDInvestmentPortfolioAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDInvestmentPortfolioAnalysisRetrieveOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateManagedInvestmentPortfolioAnalysis
      summary: Details of a new ManagedInvestmentPortfolioAnalysis instance
      description: perform an evaluation of an investment portfolio
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ManagedInvestmentPortfolioAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new ManagedInvestmentPortfolioAnalysis instance
          schema:
            $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisEvaluateOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeManagedInvestmentPortfolioAnalysisUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify, etc. the investment portfolio evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Managed Investment Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Managed Investment Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisExchangeOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeManagedInvestmentPortfolioAnalysisUpdate
      summary: Invoke an automated execute action against the ManagedInvestmentPortfolioAnalysis instance
      description: Execute an automated task for a evaluation (e.g. automated data import)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Managed Investment Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of Managed Investment Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisExecuteOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestManagedInvestmentPortfolioAnalysisUpdate
      summary: Invoke a service request action against the ManagedInvestmentPortfolioAnalysis instance
      description: Request manual intervention for an evaluation (e.g. customize analysis request)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Managed Investment Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Managed Investment Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisRequestOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveInvestmentPortfolioAnalysis
      summary: Invoke a reporting action to obtain a Managed Investment Portfolio Analysis instance related report
      description: Retrieve details about an investment portfolio analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRManagedInvestmentPortfolioAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Managed Investment Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRManagedInvestmentPortfolioAnalysisRetrieveOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeManagedInvestmentPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify etc. an analysis result
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExchangeInputModel'
      responses:
        200:
          description: Successful exchange of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExchangeOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeManagedInvestmentPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Invoke an automated execute action against the PerformanceAnalysis instance
      description: Execute an automated task for a specific type of analysis (e.g. data upload)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExecuteOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestManagedInvestmentPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Invoke a service request action against the PerformanceAnalysis instance
      description: Request manual intervention for a specific type of analysis (e.g. adapt aspects of the analysis)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRequestOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveManagedInvestmentPortfolioAnalysisPerformanceAnalysis
      summary: Invoke a reporting action to obtain a PerformanceAnalysis instance related report.
      description: Retrieve details about a specific type of investment portfolio analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQPerformanceAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRetrieveOutputModel'
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveInvestmentPortfolioAnalysisReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- InvestmentPortfolioAnalysis Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /investment-portfolio-analysis/managed-investment-portfolio-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveInvestmentPortfolioAnalysisBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'PerformanceAnalysis', ]
  /investment-portfolio-analysis/{sd-reference-id}/managed-investment-portfolio-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveInvestmentPortfolioAnalysisBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Investment Portfolio Analysis Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Managed Investment Portfolio Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- PerformanceAnalysis
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PerformanceAnalysis Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [PerformanceAnalysisID1, PerformanceAnalysisID2]
