swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Lead Opportunity Management'
 description: >

    ## Executive Summary:

    This service domain captures, classifies and track sales lead/opportunities with established clients for additional products or services. It handles the processing of the opportunity through to the point of formal offer processing.

    ## Example of Use:

    A lead is identified during a customer servicing interaction and the lead captured for subsequent follow-up

    ## Description:

    This service domain captures, evaluates and progresses identified lead/opportunities that may arise during customer relationship development, sales, servicing and fulfillment interactions. It will clarify and confirm the customer's interest and check that the product is suitable and the customer eligible prior to initiating the formal offer process (see service domain Customer Offer)

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-lead-opportunity-management/1.0.0
schemes:
 - https
paths:
  /lead-opportunity-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDLeadOpportunityManagement
      summary: Activate  a SDLeadOpportunityManagement servicing session
      description: Activate  a  SDLeadOpportunityManagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDLeadOpportunityManagement Request Payload
        schema:
          $ref: '#/definitions/SDLeadOpportunityManagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDLeadOpportunityManagementActivateOutputModel'
  /lead-opportunity-management/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDLeadOpportunityManagement
      summary: Update an active SDLeadOpportunityManagement session configuration
      description: Update an active SDLeadOpportunityManagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLeadOpportunityManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDLeadOpportunityManagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDLeadOpportunityManagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDLeadOpportunityManagementConfigureOutputModel'
  /lead-opportunity-management/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDLeadOpportunityManagement
      summary: "Capturing feedback against the SDLeadOpportunityManagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDLeadOpportunityManagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLeadOpportunityManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDLeadOpportunityManagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDLeadOpportunityManagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDLeadOpportunityManagementFeedbackOutputModel'
  /lead-opportunity-management/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDLeadOpportunityManagement
      summary: Analytical views maintained by the SDLeadOpportunityManagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDLeadOpportunityManagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLeadOpportunityManagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDLeadOpportunityManagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDLeadOpportunityManagementRetrieveOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/initiation:
    post:
      tags:
      - initiate
      operationId: initiateLeadOpportunityProcedure
      summary: Details of a new LeadOpportunityProcedure instance
      description: Initiate Lead Opportunity procedure (capture the lead details)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: LeadOpportunityProcedure Request Payload
        schema:
          $ref: '#/definitions/CRLeadOpportunityProcedureInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new LeadOpportunityProcedure instance
          schema:
            $ref: '#/definitions/CRLeadOpportunityProcedureInitiateOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateLeadOpportunityProcedure
      summary: Update to any amendable fields of the LeadOpportunityProcedure instance
      description: Update details about a Lead Opportunity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Lead Opportunity Procedure Request Payload
        schema:
          $ref: '#/definitions/CRLeadOpportunityProcedureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Lead Opportunity Procedure Instance
          schema:
            $ref: '#/definitions/CRLeadOpportunityProcedureUpdateOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlLeadOpportunityProcedureUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the processing of a Lead Opportunity (e.g. raise priority)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Lead Opportunity Procedure Request Payload
        schema:
          $ref: '#/definitions/CRLeadOpportunityProcedureControlInputModel'
      responses:
        200:
          description: Successful control of Lead Opportunity Procedure Instance
          schema:
            $ref: '#/definitions/CRLeadOpportunityProcedureControlOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeLeadOpportunityProcedureUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject etc a Lead Opportunity procedure
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Lead Opportunity Procedure Request Payload
        schema:
          $ref: '#/definitions/CRLeadOpportunityProcedureExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Lead Opportunity Procedure Instance
          schema:
            $ref: '#/definitions/CRLeadOpportunityProcedureExchangeOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveLeadOpportunityManagement
      summary: Invoke a reporting action to obtain a Lead Opportunity Procedure instance related report
      description: Retrieve details about a Lead Opportunity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRLeadOpportunityProcedureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Lead Opportunity Procedure Instance
          schema:
            $ref: '#/definitions/CRLeadOpportunityProcedureRetrieveOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/development/initiation:
    post:
      tags:
      - initiate
      operationId: initiateLeadOpportunityProcedureDevelopment
      summary: Details of a new Development instance
      description: Initiate, assign development of a Lead Opportunity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Lead Opportunity Procedure Request Payload
        schema:
          $ref: '#/definitions/BQDevelopmentInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Lead Opportunity Procedure instance
          schema:
            $ref: '#/definitions/BQDevelopmentInitiateOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/development/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateLeadOpportunityProcedureDevelopment
      summary: Update to any amendable fields of the Development instance
      description: Update details about lean/opportunity development task
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Development Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Development Request Payload
        schema:
          $ref: '#/definitions/BQDevelopmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Development Instance
          schema:
            $ref: '#/definitions/BQDevelopmentUpdateOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/development/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeLeadOpportunityProcedureDevelopmentUpdate
      summary: Invoke an automated execute action against the Development instance
      description: Execute automated action against a lead opportunity development task (e.g. generate message)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Development Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Development request payload
        schema:
          $ref: '#/definitions/BQDevelopmentExecuteInputModel'
      responses:
        200:
          description: Successful execution of Development Instance Record
          schema:
            $ref: '#/definitions/BQDevelopmentExecuteOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/development/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestLeadOpportunityProcedureDevelopmentUpdate
      summary: Invoke a service request action against the Development instance
      description: Request manual intervention in development (e.g. prospect contact)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Development Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Development request payload
        schema:
          $ref: '#/definitions/BQDevelopmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Development Instance Record
          schema:
            $ref: '#/definitions/BQDevelopmentRequestOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/development/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveLeadOpportunityProcedureDevelopment
      summary: Invoke a reporting action to obtain a Development instance related report.
      description: Retrieve details about Lead Opportunity development .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Development Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQDevelopmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Development Instance Record
          schema:
            $ref: '#/definitions/BQDevelopmentRetrieveOutputModel'
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveLeadOpportunityManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- LeadOpportunityManagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /lead-opportunity-management/lead-opportunity-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveLeadOpportunityManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Development', ]
  /lead-opportunity-management/{sd-reference-id}/lead-opportunity-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveLeadOpportunityManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Lead Opportunity Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Lead Opportunity Procedure Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Development
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Development Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [DevelopmentID1, DevelopmentID2]
