swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Legal Compliance'
 description: >

    ## Executive Summary:

    Provide specialist legal advice, assess for legal compliance and resolve legal cases as they occur

    ## Example of Use:

    Example of use:A new product design is checked against the prevailing financial laws for the target jurisdictions of delivery

    ## Description:

    This service domain oversees legal compliance related considerations for the bank. This includes interpreting the laws that govern the bank's operations and determining which laws apply in specific circumstances across the enterprise. Support and guidelines are provided to activities in the bank that are subject to specific laws and support given to address legal matters that might arise

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-legal-compliance/1.0.0
schemes:
 - https
paths:
  /legal-compliance/activation:
    post:
      tags:
      - activate
      operationId: activateSDLegalCompliance
      summary: Activate  a SDLegalCompliance servicing session
      description: Activate  a  SDLegalCompliance servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDLegalCompliance Request Payload
        schema:
          $ref: '#/definitions/SDLegalComplianceActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDLegalComplianceActivateOutputModel'
  /legal-compliance/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDLegalCompliance
      summary: Update an active SDLegalCompliance session configuration
      description: Update an active SDLegalCompliance session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLegalCompliance Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDLegalCompliance Configure Request Payload
        schema:
          $ref: '#/definitions/SDLegalComplianceConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDLegalComplianceConfigureOutputModel'
  /legal-compliance/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDLegalCompliance
      summary: "Capturing feedback against the SDLegalCompliance service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDLegalCompliance service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLegalCompliance Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDLegalCompliance Feedback Request Payload
        schema:
          $ref: '#/definitions/SDLegalComplianceFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDLegalComplianceFeedbackOutputModel'
  /legal-compliance/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDLegalCompliance
      summary: Analytical views maintained by the SDLegalCompliance service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDLegalCompliance service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDLegalCompliance Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDLegalComplianceRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDLegalComplianceRetrieveOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateLegalComplianceAssessment
      summary: Details of a new LegalComplianceAssessment instance
      description: Start a legal assessment action
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: LegalComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRLegalComplianceAssessmentEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new LegalComplianceAssessment instance
          schema:
            $ref: '#/definitions/CRLegalComplianceAssessmentEvaluateOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateLegalComplianceAssessment
      summary: Update to any amendable fields of the LegalComplianceAssessment instance
      description: Update submitted details or content for an on-going legal assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Legal Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Legal Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRLegalComplianceAssessmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Legal Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRLegalComplianceAssessmentUpdateOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeLegalComplianceAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, verify, etc. a legal determination
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Legal Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Legal Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRLegalComplianceAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Legal Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRLegalComplianceAssessmentExchangeOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestLegalComplianceAssessmentUpdate
      summary: Invoke a service request action against the LegalComplianceAssessment instance
      description: Request a review or adjudication for an assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Legal Compliance Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Legal Compliance Assessment Request Payload
        schema:
          $ref: '#/definitions/CRLegalComplianceAssessmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Legal Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRLegalComplianceAssessmentRequestOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveLegalCompliance
      summary: Invoke a reporting action to obtain a Legal Compliance Assessment instance related report
      description: Retrieve details and content from a legal assessment action
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Legal Compliance Assessment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRLegalComplianceAssessmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Legal Compliance Assessment Instance
          schema:
            $ref: '#/definitions/CRLegalComplianceAssessmentRetrieveOutputModel'
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveLegalComplianceReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- LegalCompliance Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /legal-compliance/legal-compliance-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveLegalComplianceBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /legal-compliance/{sd-reference-id}/legal-compliance-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveLegalComplianceBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Legal Compliance Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Legal Compliance Assessment Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
