swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Open Item Management'
 description: >

    ## Executive Summary:

    This service domain provides a service for handling the resolution of open items against accounts (such as overdue loan payments)

    ## Example of Use:

    Open items are cleared against an active loan facility

    ## Description:

    This service domain handles open item processing against accounts typically for loans. It enables a unit to handle resolution across multiple accounts as a specialized/centralized administrative activity

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-open-item-management/1.0.0
schemes:
 - https
paths:
  /open-item-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDOpenItemManagement
      summary: Activate  a SDOpenItemManagement servicing session
      description: Activate  a  SDOpenItemManagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDOpenItemManagement Request Payload
        schema:
          $ref: '#/definitions/SDOpenItemManagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDOpenItemManagementActivateOutputModel'
  /open-item-management/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDOpenItemManagement
      summary: Update an active SDOpenItemManagement session configuration
      description: Update an active SDOpenItemManagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDOpenItemManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDOpenItemManagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDOpenItemManagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDOpenItemManagementConfigureOutputModel'
  /open-item-management/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDOpenItemManagement
      summary: "Capturing feedback against the SDOpenItemManagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDOpenItemManagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDOpenItemManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDOpenItemManagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDOpenItemManagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDOpenItemManagementFeedbackOutputModel'
  /open-item-management/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDOpenItemManagement
      summary: Analytical views maintained by the SDOpenItemManagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDOpenItemManagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDOpenItemManagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDOpenItemManagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDOpenItemManagementRetrieveOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/initiation:
    post:
      tags:
      - initiate
      operationId: initiateOpenItemProcedure
      summary: Details of a new OpenItemProcedure instance
      description: Initiate an open item procedure
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: OpenItemProcedure Request Payload
        schema:
          $ref: '#/definitions/CROpenItemProcedureInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new OpenItemProcedure instance
          schema:
            $ref: '#/definitions/CROpenItemProcedureInitiateOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateOpenItemProcedure
      summary: Update to any amendable fields of the OpenItemProcedure instance
      description: Update details of an active open item procedure
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Open Item Procedure Request Payload
        schema:
          $ref: '#/definitions/CROpenItemProcedureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Open Item Procedure Instance
          schema:
            $ref: '#/definitions/CROpenItemProcedureUpdateOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlOpenItemProcedureUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the processing of an open item procedure (e.g. skip)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Open Item Procedure Request Payload
        schema:
          $ref: '#/definitions/CROpenItemProcedureControlInputModel'
      responses:
        200:
          description: Successful control of Open Item Procedure Instance
          schema:
            $ref: '#/definitions/CROpenItemProcedureControlOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestOpenItemProcedureUpdate
      summary: Invoke a service request action against the OpenItemProcedure instance
      description: Request manual intervention with an active open item procedure
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Open Item Procedure Request Payload
        schema:
          $ref: '#/definitions/CROpenItemProcedureRequestInputModel'
      responses:
        200:
          description: Successful requisition of Open Item Procedure Instance
          schema:
            $ref: '#/definitions/CROpenItemProcedureRequestOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveOpenItemManagement
      summary: Invoke a reporting action to obtain a Open Item Procedure instance related report
      description: Retrieve details about an open item
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CROpenItemProcedureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Open Item Procedure Instance
          schema:
            $ref: '#/definitions/CROpenItemProcedureRetrieveOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/tracking/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveOpenItemProcedureTracking
      summary: Invoke a reporting action to obtain a Tracking instance related report.
      description: Retrieve tracking details about an open item .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Tracking Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTrackingRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Tracking Instance Record
          schema:
            $ref: '#/definitions/BQTrackingRetrieveOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/repayment/initiation:
    post:
      tags:
      - initiate
      operationId: initiateOpenItemProcedureRepayment
      summary: Details of a new Repayment instance
      description: Initiate repayment transaction against an open item
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Open Item Procedure Request Payload
        schema:
          $ref: '#/definitions/BQRepaymentInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Open Item Procedure instance
          schema:
            $ref: '#/definitions/BQRepaymentInitiateOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/repayment/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateOpenItemProcedureRepayment
      summary: Update to any amendable fields of the Repayment instance
      description: Update repayment transaction details
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Repayment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Repayment Request Payload
        schema:
          $ref: '#/definitions/BQRepaymentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Repayment Instance
          schema:
            $ref: '#/definitions/BQRepaymentUpdateOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/repayment/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeOpenItemProcedureRepaymentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject, confirm etc. a repayment transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Repayment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Repayment request payload
        schema:
          $ref: '#/definitions/BQRepaymentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Repayment Instance Record
          schema:
            $ref: '#/definitions/BQRepaymentExchangeOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/repayment/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeOpenItemProcedureRepaymentUpdate
      summary: Invoke an automated execute action against the Repayment instance
      description: Execute an automated repayment task (e.g. trigger scheduled repayment)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Repayment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Repayment request payload
        schema:
          $ref: '#/definitions/BQRepaymentExecuteInputModel'
      responses:
        200:
          description: Successful execution of Repayment Instance Record
          schema:
            $ref: '#/definitions/BQRepaymentExecuteOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/repayment/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveOpenItemProcedureRepayment
      summary: Invoke a reporting action to obtain a Repayment instance related report.
      description: retrieve details about a repayment transaction .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Repayment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQRepaymentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Repayment Instance Record
          schema:
            $ref: '#/definitions/BQRepaymentRetrieveOutputModel'
  /open-item-management/{sd-reference-id}/open-item-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrieveOpenItemManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- OpenItemManagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /open-item-management/open-item-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveOpenItemManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Tracking',  'Repayment', ]
  /open-item-management/{sd-reference-id}/open-item-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveOpenItemManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Open Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Open Item Procedure Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Repayment
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Repayment Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [RepaymentID1, RepaymentID2]
