swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Payment Order'
 description: >

    ## Executive Summary:

    This service domain handles the bank-side processing of funds transfers, making the necessary bank and regulatory checks on the involved parties and applying their payment preferences where appropriate

    ## Example of Use:

    A customer transaction results in the generation of a payment order to transfer funds to an account in another bank

    ## Description:

    Payment Order handles the internal bank and compliance checks and processing of funds transfers prior to initiating the actual mechanics of transfer which is handled by the service domain Payment Execution. This includes watch-list and other regulatory checks and applying any counterparty specific limits and payment preferences. It may also oversee payment netting arrangements between the bank and other counterparties

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-payment-order/1.0.0
schemes:
 - https
paths:
  /payment-order/activation:
    post:
      tags:
      - activate
      operationId: activateSDPaymentOrder
      summary: Activate  a SDPaymentOrder servicing session
      description: Activate  a  SDPaymentOrder servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDPaymentOrder Request Payload
        schema:
          $ref: '#/definitions/SDPaymentOrderActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDPaymentOrderActivateOutputModel'
  /payment-order/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDPaymentOrder
      summary: Update an active SDPaymentOrder session configuration
      description: Update an active SDPaymentOrder session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentOrder Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPaymentOrder Configure Request Payload
        schema:
          $ref: '#/definitions/SDPaymentOrderConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDPaymentOrderConfigureOutputModel'
  /payment-order/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDPaymentOrder
      summary: "Capturing feedback against the SDPaymentOrder service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDPaymentOrder service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentOrder Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPaymentOrder Feedback Request Payload
        schema:
          $ref: '#/definitions/SDPaymentOrderFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDPaymentOrderFeedbackOutputModel'
  /payment-order/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDPaymentOrder
      summary: Analytical views maintained by the SDPaymentOrder service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDPaymentOrder service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentOrder Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDPaymentOrderRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDPaymentOrderRetrieveOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/initiation:
    post:
      tags:
      - initiate
      operationId: initiatePaymentOrderProcedure
      summary: Details of a new PaymentOrderProcedure instance
      description: a payment order procedure
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PaymentOrderProcedure Request Payload
        schema:
          $ref: '#/definitions/CRPaymentOrderProcedureInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new PaymentOrderProcedure instance
          schema:
            $ref: '#/definitions/CRPaymentOrderProcedureInitiateOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updatePaymentOrderProcedure
      summary: Update to any amendable fields of the PaymentOrderProcedure instance
      description: details of a payment order instruction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Payment Order Procedure Request Payload
        schema:
          $ref: '#/definitions/CRPaymentOrderProcedureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Payment Order Procedure Instance
          schema:
            $ref: '#/definitions/CRPaymentOrderProcedureUpdateOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentOrder
      summary: Invoke a reporting action to obtain a Payment Order Procedure instance related report
      description: details about a payment order instruction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRPaymentOrderProcedureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Payment Order Procedure Instance
          schema:
            $ref: '#/definitions/CRPaymentOrderProcedureRetrieveOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}/orderconfirmation/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentOrderProcedureOrderConfirmation
      summary: Invoke a reporting action to obtain a OrderConfirmation instance related report.
      description: details about a payment order confirmation process .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OrderConfirmation Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQOrderConfirmationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved OrderConfirmation Instance Record
          schema:
            $ref: '#/definitions/BQOrderConfirmationRetrieveOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}/executioninitiation/{bq-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlPaymentOrderProcedureExecutionInitiationUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: the payment execution processing
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: ExecutionInitiation Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ExecutionInitiation request payload
        schema:
          $ref: '#/definitions/BQExecutionInitiationControlInputModel'
      responses:
        200:
          description: Successful control of ExecutionInitiation Instance Record
          schema:
            $ref: '#/definitions/BQExecutionInitiationControlOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}/executioninitiation/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentOrderProcedureExecutionInitiation
      summary: Invoke a reporting action to obtain a ExecutionInitiation instance related report.
      description: details about the payment execution processing .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: ExecutionInitiation Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQExecutionInitiationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved ExecutionInitiation Instance Record
          schema:
            $ref: '#/definitions/BQExecutionInitiationRetrieveOutputModel'
  /payment-order/{sd-reference-id}/payment-order-procedure:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentOrderReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PaymentOrder Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /payment-order/payment-order-procedure/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentOrderBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'OrderConfirmation',  'ExecutionInitiation', ]
  /payment-order/{sd-reference-id}/payment-order-procedure/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentOrderBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Order Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Order Procedure Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- ExecutionInitiation
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- ExecutionInitiation Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ExecutionInitiationID1, ExecutionInitiationID2]
