swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Payment Initiation'
 description: >

    ## Executive Summary:

    This service domain provides a customer payment service. It captures the payer and payee details and other key properties of the payment and orchestrates the transaction. It provides support for repeating/scheduled payments

    ## Example of Use:

    An established customer transfers an amount from their current account to an overseas account for a family member. As this is a recurring transaction, the details are maintained and updated as necessary

    ## Description:

    This service domain supports payment services for consumer and business customers. Payments are made to other accounts within the bank, other banks and possibly internationally using whatever payments mechanism is suited to the transaction (See Payments Order/Execution). The service domain can support single transactions, or manage repeating/scheduled payments if requested

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-payment-initiation/1.0.0
schemes:
 - https
paths:
  /payment-initiation/activation:
    post:
      tags:
      - activate
      operationId: activateSDPaymentInitiation
      summary: Activate  a SDPaymentInitiation servicing session
      description: Activate  a  SDPaymentInitiation servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDPaymentInitiation Request Payload
        schema:
          $ref: '#/definitions/SDPaymentInitiationActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDPaymentInitiationActivateOutputModel'
  /payment-initiation/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDPaymentInitiation
      summary: Update an active SDPaymentInitiation session configuration
      description: Update an active SDPaymentInitiation session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentInitiation Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPaymentInitiation Configure Request Payload
        schema:
          $ref: '#/definitions/SDPaymentInitiationConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDPaymentInitiationConfigureOutputModel'
  /payment-initiation/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDPaymentInitiation
      summary: "Capturing feedback against the SDPaymentInitiation service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDPaymentInitiation service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentInitiation Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPaymentInitiation Feedback Request Payload
        schema:
          $ref: '#/definitions/SDPaymentInitiationFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDPaymentInitiationFeedbackOutputModel'
  /payment-initiation/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDPaymentInitiation
      summary: Analytical views maintained by the SDPaymentInitiation service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDPaymentInitiation service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPaymentInitiation Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDPaymentInitiationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDPaymentInitiationRetrieveOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/initiation:
    post:
      tags:
      - initiate
      operationId: initiatePaymentInitiationTransaction
      summary: Details of a new PaymentInitiationTransaction instance
      description: Initiate a payment transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PaymentInitiationTransaction Request Payload
        schema:
          $ref: '#/definitions/CRPaymentInitiationTransactionInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new PaymentInitiationTransaction instance
          schema:
            $ref: '#/definitions/CRPaymentInitiationTransactionInitiateOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updatePaymentInitiationTransaction
      summary: Update to any amendable fields of the PaymentInitiationTransaction instance
      description: Update details of a payment transaction instruction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Payment Initiation Transaction Request Payload
        schema:
          $ref: '#/definitions/CRPaymentInitiationTransactionUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Payment Initiation Transaction Instance
          schema:
            $ref: '#/definitions/CRPaymentInitiationTransactionUpdateOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentInitiation
      summary: Invoke a reporting action to obtain a Payment Initiation Transaction instance related report
      description: Retrieve details about a payment transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRPaymentInitiationTransactionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Payment Initiation Transaction Instance
          schema:
            $ref: '#/definitions/CRPaymentInitiationTransactionRetrieveOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/compliance/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentInitiationTransactionCompliance
      summary: Invoke a reporting action to obtain a Compliance instance related report.
      description: Retrieve details about a payment transaction compliance check .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Compliance Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQComplianceRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Compliance Instance Record
          schema:
            $ref: '#/definitions/BQComplianceRetrieveOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/fundingcheck/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentInitiationTransactionFundingCheck
      summary: Invoke a reporting action to obtain a FundingCheck instance related report.
      description: Retrieve details about a payment transaction funds available .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: FundingCheck Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQFundingCheckRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved FundingCheck Instance Record
          schema:
            $ref: '#/definitions/BQFundingCheckRetrieveOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/orderinitiation/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangePaymentInitiationTransactionOrderInitiationUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Verify or accept the payment transaction (results in a payment order)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OrderInitiation Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: OrderInitiation request payload
        schema:
          $ref: '#/definitions/BQOrderInitiationExchangeInputModel'
      responses:
        200:
          description: Successful exchange of OrderInitiation Instance Record
          schema:
            $ref: '#/definitions/BQOrderInitiationExchangeOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/orderinitiation/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrievePaymentInitiationTransactionOrderInitiation
      summary: Invoke a reporting action to obtain a OrderInitiation instance related report.
      description: Retrieve details about the payment order initiation .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OrderInitiation Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQOrderInitiationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved OrderInitiation Instance Record
          schema:
            $ref: '#/definitions/BQOrderInitiationRetrieveOutputModel'
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentInitiationReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PaymentInitiation Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /payment-initiation/payment-initiation-transaction/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentInitiationBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Compliance',  'FundingCheck',  'OrderInitiation', ]
  /payment-initiation/{sd-reference-id}/payment-initiation-transaction/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrievePaymentInitiationBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Payment Initiation Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Payment Initiation Transaction Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- OrderInitiation
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- OrderInitiation Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [OrderInitiationID1, OrderInitiationID2]
