swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Position Keeping'
 description: >

    ## Executive Summary:

    This service domain maintains a financial transaction log to support production. Reconciled financial transactions are subsequently posted to the accounting systems

    ## Example of Use:

    Any product fulfillment domain, current account, savings account, credit card, etc, delegates transaction posting/track to the Position Keeping service domain.

    ## Description:

    Maintain a log of financial transactions for management information, tracking and reconciliation purposes. It can offer utilities that enable it to maintain balances/positions, to calculate interest and to support transaction reconciliation activities The financial transactions are subsequently posted to the accounting systems

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-position-keeping/1.0.0
schemes:
 - https
paths:
  /position-keeping/activation:
    post:
      tags:
      - activate
      operationId: activateSDPositionKeeping
      summary: Activate  a SDPositionKeeping servicing session
      description: Activate  a  SDPositionKeeping servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDPositionKeeping Request Payload
        schema:
          $ref: '#/definitions/SDPositionKeepingActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDPositionKeepingActivateOutputModel'
  /position-keeping/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDPositionKeeping
      summary: Update an active SDPositionKeeping session configuration
      description: Update an active SDPositionKeeping session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionKeeping Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPositionKeeping Configure Request Payload
        schema:
          $ref: '#/definitions/SDPositionKeepingConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDPositionKeepingConfigureOutputModel'
  /position-keeping/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDPositionKeeping
      summary: "Capturing feedback against the SDPositionKeeping service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDPositionKeeping service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionKeeping Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPositionKeeping Feedback Request Payload
        schema:
          $ref: '#/definitions/SDPositionKeepingFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDPositionKeepingFeedbackOutputModel'
  /position-keeping/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDPositionKeeping
      summary: Analytical views maintained by the SDPositionKeeping service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDPositionKeeping service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionKeeping Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDPositionKeepingRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDPositionKeepingRetrieveOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialPositionLog
      summary: Details of a new FinancialPositionLog instance
      description: a position keeping transaction log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FinancialPositionLog Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionLogInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new FinancialPositionLog instance
          schema:
            $ref: '#/definitions/CRFinancialPositionLogInitiateOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialPositionLog
      summary: Update to any amendable fields of the FinancialPositionLog instance
      description: details for an active financial transaction log, including reflecting an account block (this is managed by the fulfillment SD)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position Log Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionLogUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Financial Position Log Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionLogUpdateOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlFinancialPositionLogUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: the processing of the log (e.g. suspend)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position Log Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionLogControlInputModel'
      responses:
        200:
          description: Successful control of Financial Position Log Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionLogControlOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrievePositionKeeping
      summary: Invoke a reporting action to obtain a Financial Position Log instance related report
      description: information about the log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFinancialPositionLogRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Financial Position Log Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionLogRetrieveOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialPositionLogTransactionCapture
      summary: Update to any amendable fields of the TransactionCapture instance
      description: details of a captured financial transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionCapture Request Payload
        schema:
          $ref: '#/definitions/BQTransactionCaptureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated TransactionCapture Instance
          schema:
            $ref: '#/definitions/BQTransactionCaptureUpdateOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/capture:
    put:
      tags:
      - capture
      operationId: captureFinancialPositionLogTransactionCaptureUpdate
      summary: Provide a structured input transaction/record (e.g. timesheet, event)
      description: details of a financial transaction in the log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionCapture request payload
        schema:
          $ref: '#/definitions/BQTransactionCaptureCaptureInputModel'
      responses:
        200:
          description: Successful capture of TransactionCapture Instance Record
          schema:
            $ref: '#/definitions/BQTransactionCaptureCaptureOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialPositionLogTransactionCapture
      summary: Invoke a reporting action to obtain a TransactionCapture instance related report.
      description: details of financial transactions captured in the log .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTransactionCaptureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved TransactionCapture Instance Record
          schema:
            $ref: '#/definitions/BQTransactionCaptureRetrieveOutputModel'
  /position-keeping/{sd-reference-id}/financial-position-log:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionKeepingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PositionKeeping Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /position-keeping/financial-position-log/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionKeepingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'TransactionCapture', ]
  /position-keeping/{sd-reference-id}/financial-position-log/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionKeepingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position Log Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- TransactionCapture
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionCapture Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [TransactionCaptureID1, TransactionCaptureID2]
