swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Position Management'
 description: >

    ## Executive Summary:

    The Service Domain tracks the bank's consolidated financial positions for major customers and complex market conditions

    ## Example of Use:

    A major corporate or institutional customer's consolidated position is refenced when the corporate customer sufferes a major incident

    ## Description:

    Maintain on-line and near-time cross account complex positions. Includes consolidated currency, instrument, sector and counterparty views as appropriate

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-position-management/1.0.0
schemes:
 - https
paths:
  /position-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDPositionManagement
      summary: Activate  a SDPositionManagement servicing session
      description: Activate  a  SDPositionManagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDPositionManagement Request Payload
        schema:
          $ref: '#/definitions/SDPositionManagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDPositionManagementActivateOutputModel'
  /position-management/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDPositionManagement
      summary: Update an active SDPositionManagement session configuration
      description: Update an active SDPositionManagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPositionManagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDPositionManagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDPositionManagementConfigureOutputModel'
  /position-management/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDPositionManagement
      summary: "Capturing feedback against the SDPositionManagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDPositionManagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDPositionManagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDPositionManagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDPositionManagementFeedbackOutputModel'
  /position-management/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDPositionManagement
      summary: Analytical views maintained by the SDPositionManagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDPositionManagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDPositionManagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDPositionManagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDPositionManagementRetrieveOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialPositionState
      summary: Details of a new FinancialPositionState instance
      description: Initialize a monitored financial position
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: FinancialPositionState Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionStateInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new FinancialPositionState instance
          schema:
            $ref: '#/definitions/CRFinancialPositionStateInitiateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialPositionState
      summary: Update to any amendable fields of the FinancialPositionState instance
      description: Update the settings and notification arrangements for a position
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position State Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionStateUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Financial Position State Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionStateUpdateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlFinancialPositionStateUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Change the status/handling of a monitored position
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position State Request Payload
        schema:
          $ref: '#/definitions/CRFinancialPositionStateControlInputModel'
      responses:
        200:
          description: Successful control of Financial Position State Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionStateControlOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrievePositionManagement
      summary: Invoke a reporting action to obtain a Financial Position State instance related report
      description: Get details and the current value of a monitored position
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRFinancialPositionStateRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Financial Position State Instance
          schema:
            $ref: '#/definitions/CRFinancialPositionStateRetrieveOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/trialtransaction/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialPositionStateTrialTransaction
      summary: Details of a new TrialTransaction instance
      description: Initiate the evaluation impact of a trial transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position State Request Payload
        schema:
          $ref: '#/definitions/BQTrialTransactionInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Financial Position State instance
          schema:
            $ref: '#/definitions/BQTrialTransactionInitiateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/trialtransaction/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialPositionStateTrialTransaction
      summary: Update to any amendable fields of the TrialTransaction instance
      description: Update details of a trial transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TrialTransaction Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TrialTransaction Request Payload
        schema:
          $ref: '#/definitions/BQTrialTransactionUpdateInputModel'
      responses:
        200:
          description: Successfully Updated TrialTransaction Instance
          schema:
            $ref: '#/definitions/BQTrialTransactionUpdateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/trialtransaction/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialPositionStateTrialTransaction
      summary: Invoke a reporting action to obtain a TrialTransaction instance related report.
      description: Retrieve details about a trial transaction and its position impact .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TrialTransaction Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTrialTransactionRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved TrialTransaction Instance Record
          schema:
            $ref: '#/definitions/BQTrialTransactionRetrieveOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/transactionapplication/initiation:
    post:
      tags:
      - initiate
      operationId: initiateFinancialPositionStateTransactionApplication
      summary: Details of a new TransactionApplication instance
      description: Initiate the registering of a transaction against the position
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Financial Position State Request Payload
        schema:
          $ref: '#/definitions/BQTransactionApplicationInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Financial Position State instance
          schema:
            $ref: '#/definitions/BQTransactionApplicationInitiateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/transactionapplication/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateFinancialPositionStateTransactionApplication
      summary: Update to any amendable fields of the TransactionApplication instance
      description: Update details of a registered transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionApplication Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionApplication Request Payload
        schema:
          $ref: '#/definitions/BQTransactionApplicationUpdateInputModel'
      responses:
        200:
          description: Successfully Updated TransactionApplication Instance
          schema:
            $ref: '#/definitions/BQTransactionApplicationUpdateOutputModel'
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/transactionapplication/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveFinancialPositionStateTransactionApplication
      summary: Invoke a reporting action to obtain a TransactionApplication instance related report.
      description: Retrieve details about a registered transaction and its position impact .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionApplication Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTransactionApplicationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved TransactionApplication Instance Record
          schema:
            $ref: '#/definitions/BQTransactionApplicationRetrieveOutputModel'
  /position-management/{sd-reference-id}/financial-position-state:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PositionManagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /position-management/financial-position-state/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'TrialTransaction',  'TransactionApplication', ]
  /position-management/{sd-reference-id}/financial-position-state/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrievePositionManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Position Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Financial Position State Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- TransactionApplication
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionApplication Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [TransactionApplicationID1, TransactionApplicationID2]
