swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Product Inventory Item Management'
 description: >

    ## Executive Summary:

    Maintain and distribute product inventory

    ## Example of Use:

    Newly developed product inventory is distributed as part of a product deployment project

    ## Description:

    Maintain the available central product materials inventory in coordination with distribution activities and new product/materials ordering, receipt and warehousing

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-product-inventory-item-management/1.0.0
schemes:
 - https
paths:
  /product-inventory-item-management/activation:
    post:
      tags:
      - activate
      operationId: activateSDProductInventoryItemManagement
      summary: Activate  a SDProductInventoryItemManagement servicing session
      description: Activate  a  SDProductInventoryItemManagement servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDProductInventoryItemManagement Request Payload
        schema:
          $ref: '#/definitions/SDProductInventoryItemManagementActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDProductInventoryItemManagementActivateOutputModel'
  /product-inventory-item-management/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDProductInventoryItemManagement
      summary: Update an active SDProductInventoryItemManagement session configuration
      description: Update an active SDProductInventoryItemManagement session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductInventoryItemManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductInventoryItemManagement Configure Request Payload
        schema:
          $ref: '#/definitions/SDProductInventoryItemManagementConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDProductInventoryItemManagementConfigureOutputModel'
  /product-inventory-item-management/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDProductInventoryItemManagement
      summary: "Capturing feedback against the SDProductInventoryItemManagement service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDProductInventoryItemManagement service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductInventoryItemManagement Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductInventoryItemManagement Feedback Request Payload
        schema:
          $ref: '#/definitions/SDProductInventoryItemManagementFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDProductInventoryItemManagementFeedbackOutputModel'
  /product-inventory-item-management/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDProductInventoryItemManagement
      summary: Analytical views maintained by the SDProductInventoryItemManagement service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDProductInventoryItemManagement service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductInventoryItemManagement Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDProductInventoryItemManagementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDProductInventoryItemManagementRetrieveOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductInventoryAllocation
      summary: Update to any amendable fields of the ProductInventoryAllocation instance
      description: Update details of the product inventory distribution service
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Inventory Allocation Request Payload
        schema:
          $ref: '#/definitions/CRProductInventoryAllocationUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Product Inventory Allocation Instance
          schema:
            $ref: '#/definitions/CRProductInventoryAllocationUpdateOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestProductInventoryAllocationUpdate
      summary: Invoke a service request action against the ProductInventoryAllocation instance
      description: Request manual intervention with the inventory distribution service (e.g. change arrangements for a scheduled delivery)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Inventory Allocation Request Payload
        schema:
          $ref: '#/definitions/CRProductInventoryAllocationRequestInputModel'
      responses:
        200:
          description: Successful requisition of Product Inventory Allocation Instance
          schema:
            $ref: '#/definitions/CRProductInventoryAllocationRequestOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveProductInventoryItemManagement
      summary: Invoke a reporting action to obtain a Product Inventory Allocation instance related report
      description: Retrieve details about the product inventory distribution
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRProductInventoryAllocationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Product Inventory Allocation Instance
          schema:
            $ref: '#/definitions/CRProductInventoryAllocationRetrieveOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/assignment/initiation:
    post:
      tags:
      - initiate
      operationId: initiateProductInventoryAllocationAssignment
      summary: Details of a new Assignment instance
      description: Obtain the provision of product inventory (can be internally scheduled or requested)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Inventory Allocation Request Payload
        schema:
          $ref: '#/definitions/BQAssignmentInitiateInputModel'
      responses:
        201:
          description: Successful initiation of Product Inventory Allocation instance
          schema:
            $ref: '#/definitions/BQAssignmentInitiateOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/assignment/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductInventoryAllocationAssignment
      summary: Update to any amendable fields of the Assignment instance
      description: Update details of a scheduled item assignment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Assignment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Assignment Request Payload
        schema:
          $ref: '#/definitions/BQAssignmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Assignment Instance
          schema:
            $ref: '#/definitions/BQAssignmentUpdateOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/assignment/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeProductInventoryAllocationAssignmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject etc. a schedule product item assignment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Assignment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Assignment request payload
        schema:
          $ref: '#/definitions/BQAssignmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Assignment Instance Record
          schema:
            $ref: '#/definitions/BQAssignmentExchangeOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/assignment/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestProductInventoryAllocationAssignmentUpdate
      summary: Invoke a service request action against the Assignment instance
      description: Request manual intervention with a product inventory item assignment (e.g. special delivery arrangements)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Assignment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Assignment request payload
        schema:
          $ref: '#/definitions/BQAssignmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Assignment Instance Record
          schema:
            $ref: '#/definitions/BQAssignmentRequestOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/assignment/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveProductInventoryAllocationAssignment
      summary: Invoke a reporting action to obtain a Assignment instance related report.
      description: Retrieve details about a product inventory item's distribution .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Assignment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQAssignmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved Assignment Instance Record
          schema:
            $ref: '#/definitions/BQAssignmentRetrieveOutputModel'
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductInventoryItemManagementReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- ProductInventoryItemManagement Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /product-inventory-item-management/product-inventory-allocation/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductInventoryItemManagementBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Assignment', ]
  /product-inventory-item-management/{sd-reference-id}/product-inventory-allocation/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductInventoryItemManagementBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Inventory Item Management Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Inventory Allocation Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Assignment
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Assignment Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [AssignmentID1, AssignmentID2]
