swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Product Portfolio'
 description: >

    ## Executive Summary:

    Maintain a portfolio of analytical views of the product portfolio to support product profitability and performance analysis

    ## Example of Use:

    Business development review product performance in order to target product design, marketing, sales, pricing and delivery priorities

    ## Description:

    Maintain a portfolio of view of the bank's products with key product performance data and consolidated activity details to support profitability and performance analysis across the product portfolio

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-product-portfolio/1.0.0
schemes:
 - https
paths:
  /product-portfolio/activation:
    post:
      tags:
      - activate
      operationId: activateSDProductPortfolio
      summary: Activate  a SDProductPortfolio servicing session
      description: Activate  a  SDProductPortfolio servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDProductPortfolio Request Payload
        schema:
          $ref: '#/definitions/SDProductPortfolioActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDProductPortfolioActivateOutputModel'
  /product-portfolio/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDProductPortfolio
      summary: Update an active SDProductPortfolio session configuration
      description: Update an active SDProductPortfolio session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductPortfolio Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductPortfolio Configure Request Payload
        schema:
          $ref: '#/definitions/SDProductPortfolioConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDProductPortfolioConfigureOutputModel'
  /product-portfolio/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDProductPortfolio
      summary: "Capturing feedback against the SDProductPortfolio service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDProductPortfolio service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductPortfolio Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductPortfolio Feedback Request Payload
        schema:
          $ref: '#/definitions/SDProductPortfolioFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDProductPortfolioFeedbackOutputModel'
  /product-portfolio/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDProductPortfolio
      summary: Analytical views maintained by the SDProductPortfolio service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDProductPortfolio service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductPortfolio Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDProductPortfolioRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDProductPortfolioRetrieveOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateProductPortfolioAnalysis
      summary: Details of a new ProductPortfolioAnalysis instance
      description: Evaluate product portfolio performance (trigger the analysis)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ProductPortfolioAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRProductPortfolioAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new ProductPortfolioAnalysis instance
          schema:
            $ref: '#/definitions/CRProductPortfolioAnalysisEvaluateOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductPortfolioAnalysis
      summary: Update to any amendable fields of the ProductPortfolioAnalysis instance
      description: Update settings or content for product portfolio analysis activity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/CRProductPortfolioAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Product Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRProductPortfolioAnalysisUpdateOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestProductPortfolioAnalysisUpdate
      summary: Invoke a service request action against the ProductPortfolioAnalysis instance
      description: Request manual intervention in the product portfolio analysis activity (e.g. ad-hoc request)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/CRProductPortfolioAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Product Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRProductPortfolioAnalysisRequestOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveProductPortfolio
      summary: Invoke a reporting action to obtain a Product Portfolio Analysis instance related report
      description: Retrieve details about product portfolio analysis activity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRProductPortfolioAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Product Portfolio Analysis Instance
          schema:
            $ref: '#/definitions/CRProductPortfolioAnalysisRetrieveOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateProductPortfolioAnalysisPerformanceAnalysis
      summary: Details of a new PerformanceAnalysis instance
      description: Evaluate product performance using a specific type of analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Portfolio Analysis Request Payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of Product Portfolio Analysis instance
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisEvaluateOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductPortfolioAnalysisPerformanceAnalysis
      summary: Update to any amendable fields of the PerformanceAnalysis instance
      description: Update details of a specific product performance analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis Request Payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated PerformanceAnalysis Instance
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisUpdateOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeProductPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject, verify, etc. product performance analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExchangeInputModel'
      responses:
        200:
          description: Successful exchange of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExchangeOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeProductPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Invoke an automated execute action against the PerformanceAnalysis instance
      description: Execute an automated action against on-going analysis (e.g. refresh source production data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisExecuteOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestProductPortfolioAnalysisPerformanceAnalysisUpdate
      summary: Invoke a service request action against the PerformanceAnalysis instance
      description: Request manual intervention to on-going analysis (e.g. amend analysis scope/approach)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: PerformanceAnalysis request payload
        schema:
          $ref: '#/definitions/BQPerformanceAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRequestOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/performanceanalysis/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveProductPortfolioAnalysisPerformanceAnalysis
      summary: Invoke a reporting action to obtain a PerformanceAnalysis instance related report.
      description: Retrieve details about a specific product performance analysis .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: PerformanceAnalysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQPerformanceAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved PerformanceAnalysis Instance Record
          schema:
            $ref: '#/definitions/BQPerformanceAnalysisRetrieveOutputModel'
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductPortfolioReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- ProductPortfolio Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /product-portfolio/product-portfolio-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductPortfolioBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'PerformanceAnalysis', ]
  /product-portfolio/{sd-reference-id}/product-portfolio-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductPortfolioBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Portfolio Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Portfolio Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- PerformanceAnalysis
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- PerformanceAnalysis Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [PerformanceAnalysisID1, PerformanceAnalysisID2]
