#generateNewSwagger.sh ACHFulfillment 19
#generateNewSwagger.sh AccountRecovery 18
#generateNewSwagger.sh AdvancedVoiceServicesOperations 9
#generateNewSwagger.sh CardAuthorization 14
#generateNewSwagger.sh CardCase 17
#generateNewSwagger.sh CardClearing 12
#generateNewSwagger.sh CardCollections 15
#generateNewSwagger.sh CardFinancialSettlement 11
#generateNewSwagger.sh CardNetworkParticipantFacility 11
#generateNewSwagger.sh CardTerminalAdministration 11
#generateNewSwagger.sh CardTerminalOperation 15
##generateNewSwagger.sh CardTransactionSwitch 9
#generateNewSwagger.sh CollateralAllocationManagement 10
#generateNewSwagger.sh CollateralAssetAdministration 12
#generateNewSwagger.sh ContactDialogue 32
#generateNewSwagger.sh ContactRouting 11
#generateNewSwagger.sh CorporateTreasury 12
#generateNewSwagger.sh Correspondence 18
#generateNewSwagger.sh CorrespondentBankDataManagement 4
#generateNewSwagger.sh CorrespondentBank 18
##generateNewSwagger.sh CreditChargeCard 27
#generateNewSwagger.sh CreditManagement 5
#generateNewSwagger.sh CustomerAccessEntitlement 13
#generateNewSwagger.sh CustomerAgreement 19
generateNewSwagger.sh CustomerBehavioralInsights 9
generateNewSwagger.sh CustomerBilling 15
generateNewSwagger.sh CustomerCase 14
generateNewSwagger.sh CustomerPosition 15
generateNewSwagger.sh CustomerProductServiceEligibility 10
generateNewSwagger.sh CustomerProfile 16
generateNewSwagger.sh CustomerReferenceDataManagement 22
generateNewSwagger.sh TransactionAuthorization 7
