swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Sales Product'
 description: >

    ## Executive Summary:

    A representation of a product as sold to a customer, covering the operational fulfillment requirements

    ## Example of Use:

    A bank packages its Current Account product with features suited to students as part of a prospect campaign

    ## Description:

    A sales product defines specific constraints and terms that augment the features of the base product it 'wraps'. It is used to support customization or core products to address specific market needs and opportunities with more narrowly targeted products

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-sales-product/1.0.0
schemes:
 - https
paths:
  /sales-product/activation:
    post:
      tags:
      - activate
      operationId: activateSDSalesProduct
      summary: Activate  a SDSalesProduct servicing session
      description: Activate  a  SDSalesProduct servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDSalesProduct Request Payload
        schema:
          $ref: '#/definitions/SDSalesProductActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDSalesProductActivateOutputModel'
  /sales-product/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDSalesProduct
      summary: Update an active SDSalesProduct session configuration
      description: Update an active SDSalesProduct session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSalesProduct Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDSalesProduct Configure Request Payload
        schema:
          $ref: '#/definitions/SDSalesProductConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDSalesProductConfigureOutputModel'
  /sales-product/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDSalesProduct
      summary: "Capturing feedback against the SDSalesProduct service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDSalesProduct service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSalesProduct Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDSalesProduct Feedback Request Payload
        schema:
          $ref: '#/definitions/SDSalesProductFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDSalesProductFeedbackOutputModel'
  /sales-product/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDSalesProduct
      summary: Analytical views maintained by the SDSalesProduct service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDSalesProduct service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSalesProduct Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDSalesProductRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDSalesProductRetrieveOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateProductAndServiceAgreement
      summary: Details of a new ProductAndServiceAgreement instance
      description: Set-up the operational terms agreement for a sales product instance (this links to the underlying base product)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ProductAndServiceAgreement Request Payload
        schema:
          $ref: '#/definitions/CRProductAndServiceAgreementEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new ProductAndServiceAgreement instance
          schema:
            $ref: '#/definitions/CRProductAndServiceAgreementEvaluateOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductAndServiceAgreement
      summary: Update to any amendable fields of the ProductAndServiceAgreement instance
      description: Update sales product operational terms agreement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product And Service Agreement Request Payload
        schema:
          $ref: '#/definitions/CRProductAndServiceAgreementUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Product And Service Agreement Instance
          schema:
            $ref: '#/definitions/CRProductAndServiceAgreementUpdateOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlProductAndServiceAgreementUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the execution/application of the operational terms (e.g. suspend)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product And Service Agreement Request Payload
        schema:
          $ref: '#/definitions/CRProductAndServiceAgreementControlInputModel'
      responses:
        200:
          description: Successful control of Product And Service Agreement Instance
          schema:
            $ref: '#/definitions/CRProductAndServiceAgreementControlOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSalesProduct
      summary: Invoke a reporting action to obtain a Product And Service Agreement instance related report
      description: Retrieve details about the sales product operational terms agreement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRProductAndServiceAgreementRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Product And Service Agreement Instance
          schema:
            $ref: '#/definitions/CRProductAndServiceAgreementRetrieveOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/operationalterm/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateProductAndServiceAgreementOperationalTerm
      summary: Details of a new OperationalTerm instance
      description: Set up specific operational arrangements under the agreement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product And Service Agreement Request Payload
        schema:
          $ref: '#/definitions/BQOperationalTermEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of Product And Service Agreement instance
          schema:
            $ref: '#/definitions/BQOperationalTermEvaluateOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/operationalterm/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductAndServiceAgreementOperationalTerm
      summary: Update to any amendable fields of the OperationalTerm instance
      description: Update details of an operational term arrangement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OperationalTerm Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: OperationalTerm Request Payload
        schema:
          $ref: '#/definitions/BQOperationalTermUpdateInputModel'
      responses:
        200:
          description: Successfully Updated OperationalTerm Instance
          schema:
            $ref: '#/definitions/BQOperationalTermUpdateOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/operationalterm/{bq-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeProductAndServiceAgreementOperationalTermUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject etc an operational term arrangement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OperationalTerm Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: OperationalTerm request payload
        schema:
          $ref: '#/definitions/BQOperationalTermExchangeInputModel'
      responses:
        200:
          description: Successful exchange of OperationalTerm Instance Record
          schema:
            $ref: '#/definitions/BQOperationalTermExchangeOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/operationalterm/{bq-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantProductAndServiceAgreementOperationalTermUpdate
      summary: Invoke a grant request action from the OperationalTerm instance to obtain access permission
      description: Provide a permission grant associated with an operational term arrangement
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OperationalTerm Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: OperationalTerm request payload
        schema:
          $ref: '#/definitions/BQOperationalTermGrantInputModel'
      responses:
        200:
          description: Successful grant of OperationalTerm Instance Record
          schema:
            $ref: '#/definitions/BQOperationalTermGrantOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/operationalterm/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveProductAndServiceAgreementOperationalTerm
      summary: Invoke a reporting action to obtain a OperationalTerm instance related report.
      description: Retrieve details about an individual arrangement .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: OperationalTerm Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQOperationalTermRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved OperationalTerm Instance Record
          schema:
            $ref: '#/definitions/BQOperationalTermRetrieveOutputModel'
  /sales-product/{sd-reference-id}/product-and-service-agreement:
    get:
      tags:
      - retrieve
      operationId: RetrieveSalesProductReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- SalesProduct Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /sales-product/product-and-service-agreement/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveSalesProductBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'OperationalTerm', ]
  /sales-product/{sd-reference-id}/product-and-service-agreement/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveSalesProductBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Sales Product Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product And Service Agreement Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- OperationalTerm
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- OperationalTerm Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [OperationalTermID1, OperationalTermID2]
