swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Securities Position Keeping'
 description: >

    ## Executive Summary:

    This service domain maintains a securities transaction log to support securities investment activity

    ## Example of Use:

    Example of use:An investment account is set up for a customer and the underlying securities position keeping facility is initialized to track subsequent transactions

    ## Description:

    Maintain a log of securities transactions for investment account management information, tracking and reconciliation purposes. The facility simply maintains transaction activity details for a collection of instruments, which includes dividend and other corporate action related actions where appropriate. The transaction log is used to maintain the holding positions

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-securities-position-keeping/1.0.0
schemes:
 - https
paths:
  /securities-position-keeping/activation:
    post:
      tags:
      - activate
      operationId: activateSDSecuritiesPositionKeeping
      summary: Activate  a SDSecuritiesPositionKeeping servicing session
      description: Activate  a  SDSecuritiesPositionKeeping servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDSecuritiesPositionKeeping Request Payload
        schema:
          $ref: '#/definitions/SDSecuritiesPositionKeepingActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDSecuritiesPositionKeepingActivateOutputModel'
  /securities-position-keeping/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDSecuritiesPositionKeeping
      summary: Update an active SDSecuritiesPositionKeeping session configuration
      description: Update an active SDSecuritiesPositionKeeping session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSecuritiesPositionKeeping Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDSecuritiesPositionKeeping Configure Request Payload
        schema:
          $ref: '#/definitions/SDSecuritiesPositionKeepingConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDSecuritiesPositionKeepingConfigureOutputModel'
  /securities-position-keeping/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDSecuritiesPositionKeeping
      summary: "Capturing feedback against the SDSecuritiesPositionKeeping service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDSecuritiesPositionKeeping service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSecuritiesPositionKeeping Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDSecuritiesPositionKeeping Feedback Request Payload
        schema:
          $ref: '#/definitions/SDSecuritiesPositionKeepingFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDSecuritiesPositionKeepingFeedbackOutputModel'
  /securities-position-keeping/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDSecuritiesPositionKeeping
      summary: Analytical views maintained by the SDSecuritiesPositionKeeping service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDSecuritiesPositionKeeping service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDSecuritiesPositionKeeping Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDSecuritiesPositionKeepingRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDSecuritiesPositionKeepingRetrieveOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/initiation:
    post:
      tags:
      - initiate
      operationId: initiateSecuritiesPositionLog
      summary: Details of a new SecuritiesPositionLog instance
      description: Initiate a position keeping transaction log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: SecuritiesPositionLog Request Payload
        schema:
          $ref: '#/definitions/CRSecuritiesPositionLogInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new SecuritiesPositionLog instance
          schema:
            $ref: '#/definitions/CRSecuritiesPositionLogInitiateOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateSecuritiesPositionLog
      summary: Update to any amendable fields of the SecuritiesPositionLog instance
      description: Update details for an active financial transaction log, including reflecting an account block (this is managed by the fulfillment SD)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Securities Position Log Request Payload
        schema:
          $ref: '#/definitions/CRSecuritiesPositionLogUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Securities Position Log Instance
          schema:
            $ref: '#/definitions/CRSecuritiesPositionLogUpdateOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlSecuritiesPositionLogUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Control the processing of the log (e.g. suspend)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Securities Position Log Request Payload
        schema:
          $ref: '#/definitions/CRSecuritiesPositionLogControlInputModel'
      responses:
        200:
          description: Successful control of Securities Position Log Instance
          schema:
            $ref: '#/definitions/CRSecuritiesPositionLogControlOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSecuritiesPositionKeeping
      summary: Invoke a reporting action to obtain a Securities Position Log instance related report
      description: Retrieve information about the log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRSecuritiesPositionLogRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Securities Position Log Instance
          schema:
            $ref: '#/definitions/CRSecuritiesPositionLogRetrieveOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateSecuritiesPositionLogTransactionCapture
      summary: Update to any amendable fields of the TransactionCapture instance
      description: Update details of a captured financial transaction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionCapture Request Payload
        schema:
          $ref: '#/definitions/BQTransactionCaptureUpdateInputModel'
      responses:
        200:
          description: Successfully Updated TransactionCapture Instance
          schema:
            $ref: '#/definitions/BQTransactionCaptureUpdateOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/capture:
    put:
      tags:
      - capture
      operationId: captureSecuritiesPositionLogTransactionCaptureUpdate
      summary: Provide a structured input transaction/record (e.g. timesheet, event)
      description: Capture details of a financial transaction in the log
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TransactionCapture request payload
        schema:
          $ref: '#/definitions/BQTransactionCaptureCaptureInputModel'
      responses:
        200:
          description: Successful capture of TransactionCapture Instance Record
          schema:
            $ref: '#/definitions/BQTransactionCaptureCaptureOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/transactioncapture/{bq-reference-id}/:
    get:
      tags:
      - retrieve
      operationId: retrieveSecuritiesPositionLogTransactionCapture
      summary: Invoke a reporting action to obtain a TransactionCapture instance related report.
      description: Retrieve details of financial transactions captured in the log .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TransactionCapture Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/BQTransactionCaptureRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully  Retrieved TransactionCapture Instance Record
          schema:
            $ref: '#/definitions/BQTransactionCaptureRetrieveOutputModel'
  /securities-position-keeping/{sd-reference-id}/securities-position-log:
    get:
      tags:
      - retrieve
      operationId: RetrieveSecuritiesPositionKeepingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- SecuritiesPositionKeeping Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /securities-position-keeping/securities-position-log/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveSecuritiesPositionKeepingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'TransactionCapture', ]
  /securities-position-keeping/{sd-reference-id}/securities-position-log/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveSecuritiesPositionKeepingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Securities Position Keeping Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Securities Position Log Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- TransactionCapture
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionCapture Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [TransactionCaptureID1, TransactionCaptureID2]
