swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Transaction Authorization'
 description: >

    ## Executive Summary:

    This service domain handles risk based authorization for interactive customer transactions. This combines the context (channel) transaction, customer details and recent activity analysis as appropriate. The authorization may require a specific level of party/customer authentication to get approval.

    ## Example of Use:

    A customer payment request from their current account is authorized during an assisted servicing session

    ## Description:

    This service domain is used to mitigate transaction risk for interactive product and service access fulfillment and works in collaboration with customer identity authentication services. It analyses recent customer activity in order to detect possible out of pattern/fraudulent behavior and authorizes transactions accordingly. The authorization can be subject to obtaining increased levels of customer authentication by requiring the customer to provide additional proof of identity.

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-transaction-authorization/1.0.0
schemes:
 - https
paths:
  /transaction-authorization/activation:
    post:
      tags:
      - activate
      operationId: activateSDTransactionAuthorization
      summary: Activate  a SDTransactionAuthorization servicing session
      description: Activate  a  SDTransactionAuthorization servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDTransactionAuthorization Request Payload
        schema:
          $ref: '#/definitions/SDTransactionAuthorizationActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDTransactionAuthorizationActivateOutputModel'
  /transaction-authorization/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDTransactionAuthorization
      summary: Update an active SDTransactionAuthorization session configuration
      description: Update an active SDTransactionAuthorization session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDTransactionAuthorization Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDTransactionAuthorization Configure Request Payload
        schema:
          $ref: '#/definitions/SDTransactionAuthorizationConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDTransactionAuthorizationConfigureOutputModel'
  /transaction-authorization/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDTransactionAuthorization
      summary: "Capturing feedback against the SDTransactionAuthorization service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDTransactionAuthorization service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDTransactionAuthorization Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDTransactionAuthorization Feedback Request Payload
        schema:
          $ref: '#/definitions/SDTransactionAuthorizationFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDTransactionAuthorizationFeedbackOutputModel'
  /transaction-authorization/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDTransactionAuthorization
      summary: Analytical views maintained by the SDTransactionAuthorization service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDTransactionAuthorization service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDTransactionAuthorization Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDTransactionAuthorizationRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDTransactionAuthorizationRetrieveOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateInteractiveTransactionAssessment
      summary: Details of a new InteractiveTransactionAssessment instance
      description: Evaluate a proposed interactive transaction for authorization
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new InteractiveTransactionAssessment instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentEvaluateOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateInteractiveTransactionAssessment
      summary: Update to any amendable fields of the InteractiveTransactionAssessment instance
      description: Update details of a proposed transaction for authorization
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentUpdateOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeInteractiveTransactionAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Verify, accept, override etc. a transaction authorization
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentExchangeOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeInteractiveTransactionAssessmentUpdate
      summary: Invoke an automated execute action against the InteractiveTransactionAssessment instance
      description: Execute an automated action for transaction authorization (e.g. upload data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentExecuteInputModel'
      responses:
        200:
          description: Successful execution of InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentExecuteOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestInteractiveTransactionAssessmentUpdate
      summary: Invoke a service request action against the InteractiveTransactionAssessment instance
      description: Request manual intervention (e.g. engage a specialist)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentRequestOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantInteractiveTransactionAssessmentUpdate
      summary: Invoke a grant request action from the InteractiveTransactionAssessment instance to obtain access permission
      description: Obtain an authorization grant from transaction authorization
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InteractiveTransactionAssessment Request Payload
        schema:
          $ref: '#/definitions/CRInteractiveTransactionAssessmentGrantInputModel'
      responses:
        200:
          description: Successful grant of InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentGrantOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveTransactionAuthorization
      summary: Invoke a reporting action to obtain a InteractiveTransactionAssessment instance related report
      description: Retrieve details about an interactive transaction authorization
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRInteractiveTransactionAssessmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved InteractiveTransactionAssessment Instance
          schema:
            $ref: '#/definitions/CRInteractiveTransactionAssessmentRetrieveOutputModel'
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveTransactionAuthorizationReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- TransactionAuthorization Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /transaction-authorization/interactive-transaction-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveTransactionAuthorizationBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /transaction-authorization/{sd-reference-id}/interactive-transaction-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveTransactionAuthorizationBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Transaction Authorization Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: InteractiveTransactionAssessment Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
