swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Underwriting'
 description: >

    ## Executive Summary:

    This service domain manages the underwriting decision process for products as appropriate (including many loan types and some insurance products)

    ## Example of Use:

    A corporate loan offer is processed and at the appropriate point an underwriting authorization is requested

    ## Description:

    The underwriting decision considers the ability of the borrower to finance the loan based on their known cash flows and credit worthiness. The underwriting decision refers to specific properties of the proposed loan (amount, term, repayment schedule, collateral etc.), the income and known commitments of the borrower and their credit history with the bank. The decision may factor perceived underwriting risks into the interest rate and/or collateral requirements to obtain approval

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-underwriting/1.0.0
schemes:
 - https
paths:
  /underwriting/activation:
    post:
      tags:
      - activate
      operationId: activateSDUnderwriting
      summary: Activate  a SDUnderwriting servicing session
      description: Activate  a  SDUnderwriting servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDUnderwriting Request Payload
        schema:
          $ref: '#/definitions/SDUnderwritingActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDUnderwritingActivateOutputModel'
  /underwriting/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDUnderwriting
      summary: Update an active SDUnderwriting session configuration
      description: Update an active SDUnderwriting session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDUnderwriting Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDUnderwriting Configure Request Payload
        schema:
          $ref: '#/definitions/SDUnderwritingConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDUnderwritingConfigureOutputModel'
  /underwriting/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDUnderwriting
      summary: "Capturing feedback against the SDUnderwriting service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDUnderwriting service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDUnderwriting Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDUnderwriting Feedback Request Payload
        schema:
          $ref: '#/definitions/SDUnderwritingFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDUnderwritingFeedbackOutputModel'
  /underwriting/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDUnderwriting
      summary: Analytical views maintained by the SDUnderwriting service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDUnderwriting service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDUnderwriting Servicing Session Reference
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/SDUnderwritingRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDUnderwritingRetrieveOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateUnderwritingAssessment
      summary: Details of a new UnderwritingAssessment instance
      description: Evaluate an underwriting decision
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: UnderwritingAssessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new UnderwritingAssessment instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentEvaluateOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateUnderwritingAssessment
      summary: Update to any amendable fields of the UnderwritingAssessment instance
      description: Update details for an underwriting assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Underwriting Assessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentUpdateOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeUnderwritingAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept, reject verify etc. an underwriting assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Underwriting Assessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful exchange of Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentExchangeOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeUnderwritingAssessmentUpdate
      summary: Invoke an automated execute action against the UnderwritingAssessment instance
      description: Execute an automated task for an assessment (e.g. submit transactions)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Underwriting Assessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentExecuteInputModel'
      responses:
        200:
          description: Successful execution of Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentExecuteOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestUnderwritingAssessmentUpdate
      summary: Invoke a service request action against the UnderwritingAssessment instance
      description: Request manual intervention in an assessment (e.g. discussion)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Underwriting Assessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentRequestInputModel'
      responses:
        200:
          description: Successful requisition of Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentRequestOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/grant:
    put:
      tags:
      - grant
      operationId: grantUnderwritingAssessmentUpdate
      summary: Invoke a grant request action from the UnderwritingAssessment instance to obtain access permission
      description: Obtain grant of authority from underwriting
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Underwriting Assessment Request Payload
        schema:
          $ref: '#/definitions/CRUnderwritingAssessmentGrantInputModel'
      responses:
        200:
          description: Successful grant of Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentGrantOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveUnderwriting
      summary: Invoke a reporting action to obtain a Underwriting Assessment instance related report
      description: Retrieve details about an underwriting assessment
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRUnderwritingAssessmentRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Underwriting Assessment Instance
          schema:
            $ref: '#/definitions/CRUnderwritingAssessmentRetrieveOutputModel'
  /underwriting/{sd-reference-id}/underwriting-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveUnderwritingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Underwriting Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /underwriting/underwriting-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveUnderwritingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /underwriting/{sd-reference-id}/underwriting-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveUnderwritingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Underwriting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Underwriting Assessment Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
