cp ACHFulfillment.yaml ../scripts/FinalSwaggers/Wave1and2/
cp AccountRecovery.yaml ../scripts/FinalSwaggers/Wave1and2/
cp AdvancedVoiceServicesOperations.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardAuthorization.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardCase.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardClearing.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardCollections.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardFinancialSettlement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardNetworkParticipantFacility.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardTerminalAdministration.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardTerminalOperation.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CardTransactionSwitch.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CollateralAllocationManagement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CollateralAssetAdministration.yaml ../scripts/FinalSwaggers/Wave1and2/
cp ContactDialogue.yaml ../scripts/FinalSwaggers/Wave1and2/
cp ContactRouting.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CorporateTreasury.yaml ../scripts/FinalSwaggers/Wave1and2/
cp Correspondence.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CorrespondentBankDataManagement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CorrespondentBank.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CreditChargeCard.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CreditManagement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerAccessEntitlement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerAgreement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerBehavioralInsights.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerBilling.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerCase.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerPosition.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerProductServiceEligibility.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerProfile.yaml ../scripts/FinalSwaggers/Wave1and2/
cp CustomerReferenceDataManagement.yaml ../scripts/FinalSwaggers/Wave1and2/
cp TransactionAuthorization.yaml ../scripts/FinalSwaggers/Wave1and2/
